ItemSetData = {
{ entry = 1087, name = "Fangs of the Father" },
{ entry = 1874, name = "Oath of the Aureate Sentry" },
{ entry = 1873, name = "Ageless Serpent's Foresight" },
{ entry = 1871, name = "Tireless Collector's Bounties" },
{ entry = 1869, name = "Roots of Reclaiming Blight" },
{ entry = 1867, name = "Cauldron Champion's Encore" },
{ entry = 1878, name = "Spliced Fiendtrader's Influence" },
{ entry = 1879, name = "Underpin Strongarm's Muscle" },
{ entry = 1877, name = "Currents of the Gale Sovereign" },
{ entry = 1872, name = "Jewels of the Aspectral Emissary" },
{ entry = 1875, name = "Confessor's Unshakable Virtue" },
{ entry = 1876, name = "Spectral Gambler's Last Call" },
{ entry = 1868, name = "Fel-Dealer's Contraband" },
{ entry = 1525, name = "Armor of Raging Tempests" },
{ entry = 1320, name = "Grim Inquisitor's Regalia" },
{ entry = 1310, name = "Regalia of the Skybreaker" },
{ entry = 1567, name = "Vision of the Greatwolf Outcast" },
{ entry = 1547, name = "Heartfire Sentinel's Authority" },
{ entry = 1548, name = "The Furnace Seraph's Verdict" },
{ entry = 699, name = "The Twin Blades of Azzinoth" },
{ entry = 217, name = "Judgment Armor" },
{ entry = 1870, name = "Opulent Treasurescale's Hoard" },
{ entry = 1558, name = "Screaming Torchfiend's Brutality" },
{ entry = 1557, name = "Risen Nightmare's Gravemantle" },
{ entry = 1685, name = "Rites of the Hexflame Coven" },
{ entry = 679, name = "Lightbringer Armor" },
{ entry = 1694, name = "Mane of the Greatlynx" },
{ entry = 666, name = "Avatar Regalia" },
{ entry = 694, name = "High Warlord's Redemption" },
{ entry = 523, name = "Dreadnaught's Battlegear" },
{ entry = 931, name = "Firelord's Vestments" },
{ entry = 658, name = "Mana-Etched Regalia" },
{ entry = 645, name = "Voidheart Raiment" },
{ entry = 1611, name = "Embrace of the Cinderbee" },
{ entry = 216, name = "The Ten Storms" },
{ entry = 1614, name = "Draconic Warmonger's Armor" },
{ entry = 646, name = "Corruptor Raiment" },
{ entry = 1695, name = "Husk of the Hypogeal Nemesis" },
{ entry = 321, name = "Imperial Plate" },
{ entry = 1312, name = "Titanic Onslaught Armor" },
{ entry = 213, name = "Bloodfang Armor" },
{ entry = 526, name = "Frostfire Regalia" },
{ entry = 530, name = "Cryptstalker Armor" },
{ entry = 1689, name = "Entombed Seraph's Radiance" },
{ entry = 209, name = "Battlegear of Might" },
{ entry = 651, name = "Demon Stalker Armor" },
{ entry = 1612, name = "Fury of the Stormrook" },
{ entry = 1549, name = "Lurking Specter's Shadeweave" },
{ entry = 1688, name = "Shards of Living Luster" },
{ entry = 1135, name = "White Tiger Battlegear" },
{ entry = 1552, name = "Irons of the Onyx Crucible" },
{ entry = 649, name = "Tirisfal Regalia" },
{ entry = 1565, name = "Blessings of Lunar Communion" },
{ entry = 1483, name = "Dread Sentinel's Ebony Battleplate" },
{ entry = 1569, name = "Molten Vanguard's Mortarplate" },
{ entry = 1564, name = "Zealous Pyreknight's Ardor" },
{ entry = 1697, name = "Woven Dusk" },
{ entry = 1693, name = "Destroyer's Scarred Wards" },
{ entry = 1690, name = "Gatecrasher's Fortitude" },
{ entry = 1687, name = "K'areshi Phantom's Bindings" },
{ entry = 525, name = "Vestments of Faith" },
{ entry = 1562, name = "Wayward Chronomancer's Clockwork" },
{ entry = 218, name = "Battlegear of Wrath" },
{ entry = 1507, name = "Shroud of the Demon Star" },
{ entry = 1182, name = "Celestial Harmony Regalia" },
{ entry = 1541, name = "Kinslayer's Burdens" },
{ entry = 528, name = "Redemption Armor" },
{ entry = 1542, name = "Strands of the Autumn Blaze" },
{ entry = 1308, name = "Vestments of Blind Absolution" },
{ entry = 621, name = "Netherblade" },
{ entry = 1321, name = "Garb of Venerated Spirits" },
{ entry = 1684, name = "Warsculptor's Masterwork" },
{ entry = 1528, name = "Lost Landcaller's Vesture" },
{ entry = 1527, name = "Skybound Avenger's Flightwear" },
{ entry = 163, name = "Chain of the Scarlet Crusade" },
{ entry = 622, name = "Deathmantle" },
{ entry = 1692, name = "Lightless Scavenger's Necessities" },
{ entry = 1683, name = "Woven Dawn" },
{ entry = 524, name = "Bonescythe Armor" },
{ entry = 521, name = "Dreamwalker Raiment" },
{ entry = 1284, name = "Eagletalon Battlegear" },
{ entry = 204, name = "Nightslayer Armor" },
{ entry = 529, name = "Plagueheart Raiment" },
{ entry = 668, name = "Slayer's Armor" },
{ entry = 620, name = "Assassination Armor" },
{ entry = 1302, name = "Demonbane Armor" },
{ entry = 1323, name = "Gilded Seraph's Raiment" },
{ entry = 1154, name = "Vestments of the Haunted Forest" },
{ entry = 590, name = "Grand Marshal's Battlegear" },
{ entry = 628, name = "Crystalforge Armor" },
{ entry = 1568, name = "Devout Ashdevil's Pactweave" },
{ entry = 520, name = "Ironweave Battlesuit" },
{ entry = 1544, name = "Ashen Predator's Scaleform" },
{ entry = 1496, name = "Soulblade Shadowhide" },
{ entry = 648, name = "Aldor Regalia" },
{ entry = 736, name = "Vengeful Gladiator's Battlegear" },
{ entry = 623, name = "Righteous Armor" },
{ entry = 1195, name = "Battlegear of the Unblinking Vigil" },
{ entry = 1599, name = "The Furnace Seraph's Verdict" },
{ entry = 1306, name = "Xuen's Battlegear" },
{ entry = 1281, name = "Dreadwyrm Battleplate" },
{ entry = 142, name = "Stormshroud Armor" },
{ entry = 1559, name = "Benevolent Embersage's Guidance" },
{ entry = 1561, name = "Blazing Dreamstalker's Trophies" },
{ entry = 701, name = "Merciless Gladiator's Battlegear" },
{ entry = 860, name = "Windrunner's Pursuit" },
{ entry = 1696, name = "Exhumed Centurion's Relics" },
{ entry = 1540, name = "Lingering Phantom's Encasement" },
{ entry = 1309, name = "Fanged Slayer's Armor" },
{ entry = 206, name = "Giantstalker Armor" },
{ entry = 1498, name = "Luminous Chevalier's Gallantry" },
{ entry = 632, name = "Cyclone Regalia" },
{ entry = 1526, name = "Haunted Frostbrood Remains" },
{ entry = 1307, name = "Radiant Lightbringer Armor" },
{ entry = 1325, name = "Chi-Ji's Battlegear" },
{ entry = 1311, name = "Diabolic Raiment" },
{ entry = 625, name = "Justicar Armor" },
{ entry = 684, name = "Skyshatter Regalia" },
{ entry = 1286, name = "Vestments of Enveloped Dissonance" },
{ entry = 1279, name = "Vestments of the Black Harvest" },
{ entry = 1455, name = "Regalia of Fabled Adventurers" },
{ entry = 1242, name = "Blackhand's Battlegear" },
{ entry = 215, name = "Dragonstalker Armor" },
{ entry = 1283, name = "Garb of the Astral Warden" },
{ entry = 1566, name = "Lucid Shadewalker's Silence" },
{ entry = 670, name = "Malefic Raiment" },
{ entry = 1529, name = "Stormwing Harrier's Camouflage" },
{ entry = 675, name = "Vestments of Absolution" },
{ entry = 386, name = "Warlord's Earthshaker" },
{ entry = 1143, name = "Sha-Skin Regalia" },
{ entry = 1290, name = "Regalia of Shackled Elements" },
{ entry = 1532, name = "Wrappings of the Waking Fist" },
{ entry = 1280, name = "Battlelord's Plate" },
{ entry = 124, name = "Deathbone Guardian" },
{ entry = 1480, name = "Queensguard Warbark" },
{ entry = 184, name = "Shadowcraft Armor" },
{ entry = 656, name = "Destroyer Armor" },
{ entry = 203, name = "Felheart Raiment" },
{ entry = 669, name = "Gronnstalker's Armor" },
{ entry = 673, name = "Onslaught Armor" },
{ entry = 1604, name = "Screaming Torchfiend's Brutality" },
{ entry = 1551, name = "Sinister Savant's Cursethreads" },
{ entry = 1502, name = "Tapestry of the Fixed Stars" },
{ entry = 671, name = "Tempest Regalia" },
{ entry = 599, name = "Grand Marshal's Regalia" },
{ entry = 662, name = "Hallowed Raiment" },
{ entry = 493, name = "Genesis Raiment" },
{ entry = 926, name = "Magma Plated Battlearmor" },
{ entry = 214, name = "Stormrage Raiment" },
{ entry = 207, name = "The Earthfury" },
{ entry = 1288, name = "Vestments of the Purifier" },
{ entry = 1616, name = "Draconic Warmonger's Vestments" },
{ entry = 1271, name = "Dreamgrove Raiment" },
{ entry = 741, name = "Evoker's Silk Battlegear" },
{ entry = 1238, name = "Battlegear of Guiding Light" },
{ entry = 205, name = "Cenarion Raiment" },
{ entry = 212, name = "Nemesis Raiment" },
{ entry = 1545, name = "Underlight Conjurer's Brilliance" },
{ entry = 1131, name = "Vestments of the Red Crane" },
{ entry = 1596, name = "Wrappings of the Waking Fist" },
{ entry = 1555, name = "Scalewarden's Battlegear" },
{ entry = 659, name = "Wastewalker Armor" },
{ entry = 1260, name = "Felfume Raiment" },
{ entry = 1691, name = "Sparks of Violet Rebirth" },
{ entry = 1533, name = "Virtuous Silver Cataphract" },
{ entry = 1466, name = "Garb of the Selfless" },
{ entry = 588, name = "High Warlord's Battlegear" },
{ entry = 1255, name = "Attire of Piety" },
{ entry = 511, name = "Battlegear of Heroism" },
{ entry = 1073, name = "Colossal Dragonplate Battlegear" },
{ entry = 1482, name = "Fearstalker's Ebony Battlegear" },
{ entry = 1329, name = "Felreaper Vestments" },
{ entry = 1233, name = "Living Wood Battlegear" },
{ entry = 1124, name = "Plate of the Lost Catacomb" },
{ entry = 123, name = "Bloodmail Regalia" },
{ entry = 697, name = "Champion's Redoubt" },
{ entry = 1514, name = "Drakebreaker's Armor" },
{ entry = 1574, name = "Hellbloom Battlegear" },
{ entry = 188, name = "Lightforge Armor" },
{ entry = 181, name = "Magister's Regalia" },
{ entry = 1123, name = "Battlegear of the Lost Catacomb" },
{ entry = 1534, name = "Draconic Hierophant's Finery" },
{ entry = 1543, name = "Legacy of Obsidian Secrets" },
{ entry = 1189, name = "Vestments of Winged Triumph" },
{ entry = 1304, name = "Wildstalker Armor" },
{ entry = 1270, name = "Battlegear of the Shattered Abyss" },
{ entry = 1277, name = "Battlegear of the Uncrowned" },
{ entry = 607, name = "Grand Marshal's Vindication" },
{ entry = 1531, name = "Bindings of the Crystal Scholar" },
{ entry = 208, name = "Lawbringer Armor" },
{ entry = 1056, name = "Necrotic Boneplate Armor" },
{ entry = 652, name = "Rift Stalker Armor" },
{ entry = 1070, name = "Spiritwalker's Regalia" },
{ entry = 1477, name = "Authority of Maldraxxus" },
{ entry = 1139, name = "Battlegear of the Thousandfold Blades" },
{ entry = 784, name = "Blessed Battlegear of Undead Slaying" },
{ entry = 627, name = "Crystalforge Raiment" },
{ entry = 1160, name = "Fire-Charm Vestments" },
{ entry = 1505, name = "Habiliments of the Empyrean" },
{ entry = 928, name = "Stormrider's Vestments" },
{ entry = 1292, name = "Warplate of the Obsidian Aspect" },
{ entry = 1575, name = "Hellbloom Garments" },
{ entry = 635, name = "Cataclysm Regalia" },
{ entry = 402, name = "Field Marshal's Aegis" },
{ entry = 516, name = "Soulforge Armor" },
{ entry = 509, name = "Striker's Garb" },
{ entry = 650, name = "Beast Lord Armor" },
{ entry = 605, name = "Grand Marshal's Vestments" },
{ entry = 606, name = "High Warlord's Vestments" },
{ entry = 745, name = "Opportunist's Battlegear" },
{ entry = 503, name = "Enigma Vestments" },
{ entry = 1475, name = "Guile of Maldraxxus" },
{ entry = 1563, name = "Mystic Heron's Discipline" },
{ entry = 1603, name = "Risen Nightmare's Gravemantle" },
{ entry = 677, name = "Thunderheart Regalia" },
{ entry = 202, name = "Vestments of Prophecy" },
{ entry = 211, name = "Vestments of Transcendence" },
{ entry = 654, name = "Warbringer Armor" },
{ entry = 744, name = "Kodohide Battlegear" },
{ entry = 1, name = "The Gladiator" },
{ entry = 674, name = "Absolution Regalia" },
{ entry = 1258, name = "Battlegear of Iron Wrath" },
{ entry = 512, name = "Darkmantle Armor" },
{ entry = 1536, name = "Elements of Infused Earth" },
{ entry = 1301, name = "Gravewarden Armaments" },
{ entry = 1324, name = "Light's Vanguard Battleplate" },
{ entry = 638, name = "Malorne Raiment" },
{ entry = 1240, name = "Poisoner's Battlegear" },
{ entry = 554, name = "Primal Mooncloth" },
{ entry = 1247, name = "Sootfur Garb" },
{ entry = 1538, name = "Stones of the Walking Mountain" },
{ entry = 678, name = "Thunderheart Raiment" },
{ entry = 1467, name = "Chain of the Selfless" },
{ entry = 1617, name = "Draconic Warmonger's Garb" },
{ entry = 595, name = "Grand Marshal's Pursuit" },
{ entry = 547, name = "Lieutenant Commander's Dreadgear" },
{ entry = 1133, name = "Armor of the Red Crane" },
{ entry = 1012, name = "Battleplate of Immolation" },
{ entry = 1287, name = "Battleplate of the Highlord" },
{ entry = 943, name = "Earthen Battleplate" },
{ entry = 1007, name = "Firehawk Robes of Conflagration" },
{ entry = 1261, name = "Ironpelt Armor" },
{ entry = 642, name = "Nordrassil Raiment" },
{ entry = 1243, name = "Shadow Council's Garb" },
{ entry = 1006, name = "Vestments of the Dark Phoenix" },
{ entry = 698, name = "Warlord's Aegis" },
{ entry = 161, name = "Defias Leather" },
{ entry = 660, name = "Desolation Battlegear" },
{ entry = 1556, name = "Scalewarden's Armaments" },
{ entry = 1156, name = "Armor of the Haunted Forest" },
{ entry = 1064, name = "Battleplate of Radiant Glory" },
{ entry = 1319, name = "Juggernaut Battlegear" },
{ entry = 1291, name = "Legacy of Azj'Aqir" },
{ entry = 1501, name = "Mercurial Punisher's Painweave" },
{ entry = 672, name = "Onslaught Battlegear" },
{ entry = 1141, name = "Regalia of the Firebird" },
{ entry = 1069, name = "Spiritwalker's Vestments" },
{ entry = 1275, name = "Battleplate of the Silver Hand" },
{ entry = 1521, name = "Drape of Raging Tempests" },
{ entry = 637, name = "Moonglade Raiment" },
{ entry = 1553, name = "Scalewarden's Garments" },
{ entry = 1336, name = "Thundercrash Armor" },
{ entry = 1074, name = "Colossal Dragonplate Armor" },
{ entry = 681, name = "Lightbringer Raiment" },
{ entry = 1186, name = "Regalia of Ternion Glory" },
{ entry = 1537, name = "Scalesworn Cultist's Habit" },
{ entry = 1462, name = "Soulbreaker's Ebony Vestments" },
{ entry = 1062, name = "Time Lord's Regalia" },
{ entry = 782, name = "Undead Slayer's Blessed Armor" },
{ entry = 383, name = "Warlord's Battlegear" },
{ entry = 937, name = "Wind Dancer's Regalia" },
{ entry = 1241, name = "Windspeaker's Regalia" },
{ entry = 121, name = "Cadaverous Garb" },
{ entry = 537, name = "Champion's Battlearmor" },
{ entry = 1335, name = "Venombite Garb" },
{ entry = 201, name = "Arcanist Regalia" },
{ entry = 1185, name = "Barbed Assassin Battlegear" },
{ entry = 1200, name = "Battleplate of Cyclopean Dread" },
{ entry = 1183, name = "Celestial Harmony Battlegear" },
{ entry = 496, name = "Conqueror's Battlegear" },
{ entry = 1546, name = "Fangs of the Vermillion Forge" },
{ entry = 702, name = "Merciless Gladiator's Dreadgear" },
{ entry = 643, name = "Nordrassil Regalia" },
{ entry = 619, name = "Primal Intent" },
{ entry = 1285, name = "Regalia of Everburning Knowledge" },
{ entry = 1158, name = "Regalia of the Chromatic Hydra" },
{ entry = 553, name = "Shadow's Embrace" },
{ entry = 501, name = "Stormcaller's Garb" },
{ entry = 730, name = "Vengeful Gladiator's Vestments" },
{ entry = 396, name = "Warlord's Pursuit" },
{ entry = 1605, name = "Wayward Chronomancer's Clockwork" },
{ entry = 1061, name = "Wyrmstalker Battlegear" },
{ entry = 653, name = "Bold Armor" },
{ entry = 1108, name = "Gladiator's Pursuit" },
{ entry = 608, name = "High Warlord's Vindication" },
{ entry = 647, name = "Incanter's Regalia" },
{ entry = 122, name = "Necropile Raiment" },
{ entry = 444, name = "The Darksoul" },
{ entry = 1191, name = "Armor of Seven Sacred Seals" },
{ entry = 505, name = "Avenger's Battlegear" },
{ entry = 1328, name = "Bearmantle Battlegear" },
{ entry = 497, name = "Deathdealer's Embrace" },
{ entry = 1330, name = "Dreadwake Armor" },
{ entry = 1481, name = "Ebony Death Shroud Armor" },
{ entry = 1001, name = "Elementium Deathplate Battlearmor" },
{ entry = 1256, name = "Felblade Armor" },
{ entry = 894, name = "Frost Witch's Battlegear" },
{ entry = 899, name = "Lightsworn Garb" },
{ entry = 713, name = "Merciless Gladiator's Vestments" },
{ entry = 1004, name = "Obsidian Arborweave Vestments" },
{ entry = 1067, name = "Regalia of Dying Light" },
{ entry = 1550, name = "Runes of the Cinderwolf" },
{ entry = 1535, name = "Vault Delver's Toolkit" },
{ entry = 552, name = "Wrath of Spellfire" },
{ entry = 183, name = "Dreadmist Raiment" },
{ entry = 1573, name = "Hellbloom Chainmail" },
{ entry = 750, name = "Savage Plate Battlegear" },
{ entry = 1523, name = "Shroud of Raging Tempests" },
{ entry = 1235, name = "Arcanoshatter Regalia" },
{ entry = 1190, name = "Battlegear of Winged Triumph" },
{ entry = 1068, name = "Blackfang Battleweave" },
{ entry = 883, name = "Bloodmage's Regalia" },
{ entry = 1289, name = "Doomblade Battlegear" },
{ entry = 1504, name = "Garb of the Grand Upwelling" },
{ entry = 583, name = "Gladiator's Vindication" },
{ entry = 1510, name = "Horizon Strider's Garments" },
{ entry = 663, name = "Incarnate Raiment" },
{ entry = 664, name = "Incarnate Regalia" },
{ entry = 1167, name = "Nine-Tail Battlegear" },
{ entry = 1234, name = "Ogreskull Boneplate Battlegear" },
{ entry = 1138, name = "Regalia of the Guardian Serpent" },
{ entry = 682, name = "Skyshatter Harness" },
{ entry = 1239, name = "Soul Priest's Raiment" },
{ entry = 527, name = "The Earthshatterer" },
{ entry = 849, name = "Velen's Regalia" },
{ entry = 1140, name = "Vestments of the Firebird" },
{ entry = 655, name = "Warbringer Battlegear" },
{ entry = 1560, name = "Werynkeeper's Timeless Vigil" },
{ entry = 1129, name = "Yaungol Slayer Battlegear" },
{ entry = 186, name = "Beaststalker Armor" },
{ entry = 1269, name = "Deathlord's Battleplate" },
{ entry = 187, name = "The Elements" },
{ entry = 1266, name = "Illidari Slayer" },
{ entry = 781, name = "Blessed Regalia of Undead Cleansing" },
{ entry = 629, name = "Crystalforge Battlegear" },
{ entry = 1520, name = "Dragon Rider's Gear" },
{ entry = 513, name = "Feralheart Raiment" },
{ entry = 1598, name = "Heartfire Sentinel's Authority" },
{ entry = 1251, name = "Raiment of the Arcanic Conclave" },
{ entry = 1322, name = "Regalia of the Dashing Scoundrel" },
{ entry = 833, name = "Sanctification Regalia" },
{ entry = 1303, name = "Stormheart Raiment" },
{ entry = 732, name = "Vengeful Gladiator's Earthshaker" },
{ entry = 728, name = "Vengeful Gladiator's Investiture" },
{ entry = 661, name = "Doomplate Battlegear" },
{ entry = 162, name = "Embrace of the Viper" },
{ entry = 1461, name = "Faewoven Regalia" },
{ entry = 575, name = "Felstalker Armor" },
{ entry = 597, name = "Grand Marshal's Raiment" },
{ entry = 598, name = "High Warlord's Raiment" },
{ entry = 1147, name = "Tradition of Cooking" },
{ entry = 1459, name = "Vestments of the Selfless" },
{ entry = 1065, name = "Armor of Radiant Glory" },
{ entry = 1152, name = "Battleplate of the All-Consuming Maw" },
{ entry = 636, name = "Cataclysm Harness" },
{ entry = 631, name = "Cyclone Raiment" },
{ entry = 1259, name = "Deathrattle Regalia" },
{ entry = 581, name = "Gladiator's Raiment" },
{ entry = 685, name = "Gladiator's Refuge" },
{ entry = 1602, name = "Irons of the Onyx Crucible" },
{ entry = 624, name = "Justicar Raiment" },
{ entry = 900, name = "Lightsworn Battlegear" },
{ entry = 715, name = "Merciless Gladiator's Wartide" },
{ entry = 936, name = "Mercurial Regalia" },
{ entry = 935, name = "Mercurial Vestments" },
{ entry = 1010, name = "Regalia of the Cleansing Flame" },
{ entry = 940, name = "Regalia of the Raging Elements" },
{ entry = 1170, name = "Regalia of the Witch Doctor" },
{ entry = 1601, name = "Sinister Savant's Cursethreads" },
{ entry = 1500, name = "The First Eidolon's Soulsteel" },
{ entry = 1192, name = "Vestments of Seven Sacred Seals" },
{ entry = 1072, name = "Vestments of the Faceless Shroud" },
{ entry = 1606, name = "Vision of the Greatwolf Outcast" },
{ entry = 387, name = "Warlord's Regalia" },
{ entry = 1686, name = "Waves of the Forgotten Reservoir" },
{ entry = 1136, name = "White Tiger Plate" },
{ entry = 562, name = "Adamantite Battlegear" },
{ entry = 489, name = "Black Dragon Mail" },
{ entry = 752, name = "Crusader's Scaled Battlegear" },
{ entry = 1293, name = "March of the Legion" },
{ entry = 1276, name = "Regalia of the High Priest" },
{ entry = 182, name = "Vestments of the Devout" },
{ entry = 1468, name = "Vestments of the Selfless" },
{ entry = 185, name = "Wildheart Raiment" },
{ entry = 1476, name = "Alacrity of Maldraxxus" },
{ entry = 1506, name = "Armaments of the Infinite Infantry" },
{ entry = 939, name = "Battlegear of the Raging Elements" },
{ entry = 1157, name = "Battlegear of the Saurok Stalker" },
{ entry = 515, name = "Beastmaster Armor" },
{ entry = 783, name = "Blessed Garb of the Undead Slayer" },
{ entry = 1000, name = "Elementium Deathplate Battlegear" },
{ entry = 1503, name = "Erudite Occultist's Vestments" },
{ entry = 384, name = "Field Marshal's Battlegear" },
{ entry = 579, name = "Gladiator's Regalia" },
{ entry = 680, name = "Lightbringer Battlegear" },
{ entry = 706, name = "Merciless Gladiator's Pursuit" },
{ entry = 710, name = "Merciless Gladiator's Regalia" },
{ entry = 711, name = "Merciless Gladiator's Sanctuary" },
{ entry = 1057, name = "Necrotic Boneplate Battlegear" },
{ entry = 210, name = "Netherwind Regalia" },
{ entry = 1164, name = "Plate of the Lightning Emperor" },
{ entry = 1130, name = "Regalia of the Burning Scroll" },
{ entry = 897, name = "Scourgelord's Battlegear" },
{ entry = 1499, name = "Theurgic Starspeaker's Regalia" },
{ entry = 1009, name = "Vestments of the Cleansing Flame" },
{ entry = 1165, name = "Vestments of the Exorcist" },
{ entry = 514, name = "Vestments of the Virtuous" },
{ entry = 390, name = "Warlord's Raiment" },
{ entry = 1111, name = "Gladiator's Vindication" },
{ entry = 1572, name = "Hellbloom Armaments" },
{ entry = 587, name = "High Warlord's Aegis" },
{ entry = 718, name = "Lieutenant Commander's Earthshaker" },
{ entry = 1332, name = "Umbra-Weaver's Portent" },
{ entry = 945, name = "Deathspeaker" },
{ entry = 141, name = "Volcanic Armor" },
{ entry = 1128, name = "Armor of the Eternal Blossom" },
{ entry = 1008, name = "Balespider's Burning Vestments" },
{ entry = 1194, name = "Chronomancer Regalia" },
{ entry = 835, name = "Darkruned Plate" },
{ entry = 1249, name = "Demongaze Armor" },
{ entry = 394, name = "Field Marshal's Vestments" },
{ entry = 507, name = "Garments of the Oracle" },
{ entry = 567, name = "Gladiator's Battlegear" },
{ entry = 687, name = "Gladiator's Investiture" },
{ entry = 586, name = "Gladiator's Pursuit" },
{ entry = 1613, name = "Ky'veza's Cruel Implements" },
{ entry = 1171, name = "Regalia of the Thousandfold Hells" },
{ entry = 933, name = "Reinforced Sapphirium Regalia" },
{ entry = 1236, name = "Rylakstalker's Battlegear" },
{ entry = 832, name = "Sanctification Garb" },
{ entry = 1530, name = "Scales of the Awakened" },
{ entry = 898, name = "Scourgelord's Plate" },
{ entry = 683, name = "Skyshatter Raiment" },
{ entry = 261, name = "Spirit of Eskhandar" },
{ entry = 667, name = "The Twin Stars" },
{ entry = 877, name = "Turalyon's Battlegear" },
{ entry = 1282, name = "Vestment of Second Sight" },
{ entry = 1016, name = "Volcanic Regalia" },
{ entry = 896, name = "Ymirjar Lord's Plate" },
{ entry = 967, name = "Bloodthirsty Dragonscale" },
{ entry = 965, name = "Bloodthirsty Leather" },
{ entry = 963, name = "Bloodthirsty Pyrium" },
{ entry = 345, name = "Champion's Threads" },
{ entry = 143, name = "Devilsaur Armor" },
{ entry = 1117, name = "Gladiator's Felshroud" },
{ entry = 1274, name = "Grandmaster's Finery" },
{ entry = 546, name = "Lieutenant Commander's Arcanum" },
{ entry = 362, name = "Lieutenant Commander's Pursuit" },
{ entry = 1278, name = "Raiment of the Farseer" },
{ entry = 740, name = "Satin Battlegear" },
{ entry = 1524, name = "Scales of Raging Tempests" },
{ entry = 765, name = "Gladiator's Battlegear" },
{ entry = 665, name = "Avatar Raiment" },
{ entry = 1237, name = "Battlegear of the Somber Gaze" },
{ entry = 495, name = "Battlegear of Unyielding Strength" },
{ entry = 633, name = "Cyclone Harness" },
{ entry = 884, name = "Dark Coven's Regalia" },
{ entry = 1058, name = "Deep Earth Battlegarb" },
{ entry = 1159, name = "Fire-Charm Battlegear" },
{ entry = 887, name = "Lasherweave Garb" },
{ entry = 878, name = "Liadrin's Battlegear" },
{ entry = 930, name = "Lightning-Charged Battlegear" },
{ entry = 1017, name = "Molten Giant Warplate" },
{ entry = 1011, name = "Regalia of Immolation" },
{ entry = 1305, name = "Regalia of the Arcane Tempest" },
{ entry = 1155, name = "Regalia of the Haunted Forest" },
{ entry = 1071, name = "Spiritwalker's Battlegear" },
{ entry = 1595, name = "Stormwing Harrier's Camouflage" },
{ entry = 510, name = "Trappings of the Unseen Path" },
{ entry = 734, name = "Vengeful Gladiator's Dreadgear" },
{ entry = 938, name = "Vestments of the Raging Elements" },
{ entry = 1198, name = "Vestments of the Shattered Vale" },
{ entry = 571, name = "Whitemend Wisdom" },
{ entry = 850, name = "Zabra's Regalia" },
{ entry = 966, name = "Bloodthirsty Wyrmhide" },
{ entry = 347, name = "Champion's Vestments" },
{ entry = 1513, name = "Drakebreaker's Vestments" },
{ entry = 1338, name = "Frenzied Battleplate" },
{ entry = 1146, name = "Gladiator's Raiment" },
{ entry = 691, name = "Grand Marshal's Investiture" },
{ entry = 1272, name = "Guise of the Unseen Path" },
{ entry = 592, name = "High Warlord's Dreadgear" },
{ entry = 556, name = "Imbued Netherweave" },
{ entry = 346, name = "Lieutenant Commander's Threads" },
{ entry = 1295, name = "Nightwell Arcanum" },
{ entry = 814, name = "Ornate Saronite Battlegear" },
{ entry = 747, name = "Seer's Ringmail Battlegear" },
{ entry = 81, name = "The Postmaster" },
{ entry = 630, name = "Tidefury Raiment" },
{ entry = 799, name = "Dreamwalker Regalia" },
{ entry = 768, name = "Gladiator's Desecration" },
{ entry = 1144, name = "Battleplate of Resounding Rings" },
{ entry = 885, name = "Crimson Acolyte's Raiment" },
{ entry = 518, name = "Deathmist Raiment" },
{ entry = 942, name = "Earthen Warplate" },
{ entry = 1248, name = "Ebonflame Raiment" },
{ entry = 395, name = "Field Marshal's Pursuit" },
{ entry = 1005, name = "Flamewaker's Battlegear" },
{ entry = 858, name = "Garona's Battlegear" },
{ entry = 584, name = "Gladiator's Sanctuary" },
{ entry = 626, name = "Justicar Battlegear" },
{ entry = 901, name = "Lightsworn Plate" },
{ entry = 616, name = "Netherscale Armor" },
{ entry = 1003, name = "Obsidian Arborweave Regalia" },
{ entry = 1145, name = "Plate of Resounding Rings" },
{ entry = 941, name = "Shadowflame Regalia" },
{ entry = 1597, name = "Strands of the Autumn Blaze" },
{ entry = 494, name = "Symbols of Unending Life" },
{ entry = 676, name = "Thunderheart Harness" },
{ entry = 618, name = "Windhawk Armor" },
{ entry = 1515, name = "Woven Chronocloth" },
{ entry = 189, name = "Battlegear of Valor" },
{ entry = 539, name = "Champion's Refuge" },
{ entry = 751, name = "Crusader's Ornamented Battlegear" },
{ entry = 41, name = "Dal'Rend's Arms" },
{ entry = 1615, name = "Draconic Warmonger's Chainmail" },
{ entry = 742, name = "Dragonhide Battlegear" },
{ entry = 1511, name = "Drakebreaker's Garb" },
{ entry = 563, name = "Enchanted Adamantite Armor" },
{ entry = 569, name = "Faith in Felsteel" },
{ entry = 564, name = "Flame Guard" },
{ entry = 1112, name = "Gladiator's Investiture" },
{ entry = 692, name = "High Warlord's Investiture" },
{ entry = 1244, name = "Might of the Warsong" },
{ entry = 749, name = "Stalker's Chain Battlegear" },
{ entry = 468, name = "The Highlander's Resolve" },
{ entry = 1273, name = "Vesture of Tirisgarde" },
{ entry = 944, name = "Spiritmender" },
{ entry = 812, name = "Spring Tuxedo" },
{ entry = 787, name = "Dreadnaught Plate" },
{ entry = 805, name = "Garb of Faith" },
{ entry = 1516, name = "Azureweave Vestments" },
{ entry = 1199, name = "Battlegear of the Shattered Vale" },
{ entry = 657, name = "Destroyer Battlegear" },
{ entry = 388, name = "Field Marshal's Regalia" },
{ entry = 893, name = "Frost Witch's Regalia" },
{ entry = 580, name = "Gladiator's Thunderfist" },
{ entry = 482, name = "Illusionist's Attire" },
{ entry = 500, name = "Implements of Unspoken Names" },
{ entry = 872, name = "Koltira's Battlegear" },
{ entry = 1600, name = "Lurking Specter's Shadeweave" },
{ entry = 478, name = "Madcap's Outfit" },
{ entry = 1262, name = "Rancorbite Battlegear" },
{ entry = 934, name = "Reinforced Sapphirium Battlearmor" },
{ entry = 1327, name = "Serpentstalker Guise" },
{ entry = 890, name = "Shadowblade's Battlegear" },
{ entry = 882, name = "Shiny Shard of the Gods" },
{ entry = 517, name = "Sorcerer's Regalia" },
{ entry = 862, name = "Thrall's Garb" },
{ entry = 729, name = "Vengeful Gladiator's Raiment" },
{ entry = 722, name = "Vengeful Gladiator's Wildhide" },
{ entry = 1187, name = "Vestments of Ternion Glory" },
{ entry = 1137, name = "Vestments of the Guardian Serpent" },
{ entry = 859, name = "Windrunner's Battlegear" },
{ entry = 558, name = "Arcanoweave Vestments" },
{ entry = 421, name = "Bloodvine Garb" },
{ entry = 491, name = "Blue Dragon Mail" },
{ entry = 522, name = "Champion's Guard" },
{ entry = 538, name = "Champion's Stormcaller" },
{ entry = 738, name = "Dreadweave Battlegear" },
{ entry = 535, name = "Garb of the Undead Slayer" },
{ entry = 1113, name = "Gladiator's Vestments" },
{ entry = 693, name = "Grand Marshal's Redemption" },
{ entry = 1294, name = "Journey Through Time" },
{ entry = 282, name = "Lieutenant Commander's Battlegear" },
{ entry = 739, name = "Mooncloth Battlegear" },
{ entry = 1478, name = "Oakheart Raiment" },
{ entry = 1479, name = "Runewarden's Guise" },
{ entry = 486, name = "The Defiler's Purpose" },
{ entry = 908, name = "The Defiler's Resolve" },
{ entry = 561, name = "Fel Iron Chain" },
{ entry = 763, name = "Frostwoven Power" },
{ entry = 785, name = "Midsummer Reveler" },
{ entry = 614, name = "Wild Draenish Armor" },
{ entry = 778, name = "Gladiator's Raiment" },
{ entry = 775, name = "Gladiator's Sanctuary" },
{ entry = 789, name = "Redemption Battlegear" },
{ entry = 891, name = "Ahn'Kahar Blood Hunter's Battlegear" },
{ entry = 1132, name = "Battlegear of the Red Crane" },
{ entry = 1180, name = "Battleplate of the Prehistoric Marauder" },
{ entry = 837, name = "Deathbringer Garb" },
{ entry = 1060, name = "Deep Earth Vestments" },
{ entry = 499, name = "Doomcaller's Attire" },
{ entry = 1161, name = "Fire-Charm Armor" },
{ entry = 582, name = "Gladiator's Aegis" },
{ entry = 568, name = "Gladiator's Dreadgear" },
{ entry = 577, name = "Gladiator's Vestments" },
{ entry = 686, name = "Gladiator's Wartide" },
{ entry = 585, name = "Gladiator's Wildhide" },
{ entry = 846, name = "Kel'Thuzad's Regalia" },
{ entry = 889, name = "Lasherweave Battlegear" },
{ entry = 855, name = "Malfurion's Battlegear" },
{ entry = 851, name = "Malfurion's Garb" },
{ entry = 639, name = "Malorne Regalia" },
{ entry = 704, name = "Merciless Gladiator's Felshroud" },
{ entry = 714, name = "Merciless Gladiator's Vindication" },
{ entry = 865, name = "Nobundo's Battlegear" },
{ entry = 1002, name = "Obsidian Arborweave Battlegarb" },
{ entry = 1201, name = "Plate of Cyclopean Dread" },
{ entry = 1181, name = "Regalia of the Horned Nightmare" },
{ entry = 519, name = "The Five Thunders" },
{ entry = 863, name = "Thrall's Regalia" },
{ entry = 504, name = "Trappings of Vaulted Secrets" },

}