ItemSetData = {
{ entry = 1, name = "The Gladiator" },
{ entry = 41, name = "Dal'Rend's Arms" },
{ entry = 65, name = "Spider's Kiss" },
{ entry = 81, name = "The Postmaster" },
{ entry = 121, name = "Cadaverous Garb" },
{ entry = 122, name = "Necropile Raiment" },
{ entry = 123, name = "Bloodmail Regalia" },
{ entry = 124, name = "Deathbone Guardian" },
{ entry = 141, name = "Volcanic Armor" },
{ entry = 142, name = "Stormshroud Armor" },
{ entry = 143, name = "Devilsaur Armor" },
{ entry = 144, name = "Ironfeather Armor" },
{ entry = 161, name = "Defias Leather" },
{ entry = 162, name = "Embrace of the Viper" },
{ entry = 163, name = "Chain of the Scarlet Crusade" },
{ entry = 181, name = "Magister's Regalia" },
{ entry = 182, name = "Vestments of the Devout" },
{ entry = 183, name = "Dreadmist Raiment" },
{ entry = 184, name = "Shadowcraft Armor" },
{ entry = 185, name = "Wildheart Raiment" },
{ entry = 186, name = "Beaststalker Armor" },
{ entry = 187, name = "The Elements" },
{ entry = 188, name = "Lightforge Armor" },
{ entry = 189, name = "Battlegear of Valor" },
{ entry = 201, name = "Arcanist Regalia" },
{ entry = 202, name = "Vestments of Prophecy" },
{ entry = 203, name = "Felheart Raiment" },
{ entry = 204, name = "Nightslayer Armor" },
{ entry = 205, name = "Cenarion Raiment" },
{ entry = 206, name = "Giantstalker Armor" },
{ entry = 207, name = "The Earthfury" },
{ entry = 208, name = "Lawbringer Armor" },
{ entry = 209, name = "Battlegear of Might" },
{ entry = 210, name = "Netherwind Regalia" },
{ entry = 211, name = "Vestments of Transcendence" },
{ entry = 212, name = "Nemesis Raiment" },
{ entry = 213, name = "Bloodfang Armor" },
{ entry = 214, name = "Stormrage Raiment" },
{ entry = 215, name = "Dragonstalker Armor" },
{ entry = 216, name = "The Ten Storms" },
{ entry = 217, name = "Judgment Armor" },
{ entry = 218, name = "Battlegear of Wrath" },
{ entry = 221, name = "Garb of Thero-shan" },
{ entry = 241, name = "Shard of the Gods" },
{ entry = 261, name = "Spirit of Eskhandar" },
{ entry = 281, name = "Champion's Battlegear" },
{ entry = 282, name = "Lieutenant Commander's Battlegear" },
{ entry = 301, name = "Champion's Earthshaker" },
{ entry = 321, name = "Imperial Plate" },
{ entry = 341, name = "Champion's Regalia" },
{ entry = 342, name = "Champion's Raiment" },
{ entry = 343, name = "Lieutenant Commander's Regalia" },
{ entry = 344, name = "Lieutenant Commander's Raiment" },
{ entry = 345, name = "Champion's Threads" },
{ entry = 346, name = "Lieutenant Commander's Threads" },
{ entry = 347, name = "Champion's Vestments" },
{ entry = 348, name = "Lieutenant Commander's Vestments" },
{ entry = 361, name = "Champion's Pursuit" },
{ entry = 362, name = "Lieutenant Commander's Pursuit" },
{ entry = 381, name = "Lieutenant Commander's Sanctuary" },
{ entry = 382, name = "Champion's Sanctuary" },
{ entry = 383, name = "Warlord's Battlegear" },
{ entry = 384, name = "Field Marshal's Battlegear" },
{ entry = 386, name = "Warlord's Earthshaker" },
{ entry = 387, name = "Warlord's Regalia" },
{ entry = 388, name = "Field Marshal's Regalia" },
{ entry = 389, name = "Field Marshal's Raiment" },
{ entry = 390, name = "Warlord's Raiment" },
{ entry = 391, name = "Warlord's Threads" },
{ entry = 392, name = "Field Marshal's Threads" },
{ entry = 393, name = "Warlord's Vestments" },
{ entry = 394, name = "Field Marshal's Vestments" },
{ entry = 395, name = "Field Marshal's Pursuit" },
{ entry = 396, name = "Warlord's Pursuit" },
{ entry = 397, name = "Field Marshal's Sanctuary" },
{ entry = 398, name = "Warlord's Sanctuary" },
{ entry = 401, name = "Lieutenant Commander's Aegis" },
{ entry = 402, name = "Field Marshal's Aegis" },
{ entry = 421, name = "Bloodvine Garb" },
{ entry = 441, name = "Primal Batskin" },
{ entry = 442, name = "Blood Tiger Harness" },
{ entry = 443, name = "Bloodsoul Embrace" },
{ entry = 444, name = "The Darksoul" },
{ entry = 461, name = "The Twin Blades of Hakkari" },
{ entry = 462, name = "Zanzil's Concentration" },
{ entry = 463, name = "Primal Blessing" },
{ entry = 464, name = "Overlord's Resolution" },
{ entry = 465, name = "Prayer of the Primal" },
{ entry = 466, name = "Major Mojo Infusion" },
{ entry = 467, name = "The Highlander's Resolution" },
{ entry = 468, name = "The Highlander's Resolve" },
{ entry = 469, name = "The Highlander's Determination" },
{ entry = 470, name = "The Highlander's Fortitude" },
{ entry = 471, name = "The Highlander's Purpose" },
{ entry = 472, name = "The Highlander's Will" },
{ entry = 473, name = "The Highlander's Intent" },
{ entry = 474, name = "Vindicator's Battlegear" },
{ entry = 475, name = "Freethinker's Armor" },
{ entry = 476, name = "Augur's Regalia" },
{ entry = 477, name = "Predator's Armor" },
{ entry = 478, name = "Madcap's Outfit" },
{ entry = 479, name = "Haruspex's Garb" },
{ entry = 480, name = "Confessor's Raiment" },
{ entry = 481, name = "Demoniac's Threads" },
{ entry = 482, name = "Illusionist's Attire" },
{ entry = 483, name = "The Defiler's Determination" },
{ entry = 484, name = "The Defiler's Fortitude" },
{ entry = 485, name = "The Defiler's Intent" },
{ entry = 486, name = "The Defiler's Purpose" },
{ entry = 487, name = "The Defiler's Resolution" },
{ entry = 488, name = "The Defiler's Will" },
{ entry = 489, name = "Black Dragon Mail" },
{ entry = 490, name = "Green Dragon Mail" },
{ entry = 491, name = "Blue Dragon Mail" },
{ entry = 492, name = "Twilight Trappings" },
{ entry = 493, name = "Genesis Raiment" },
{ entry = 494, name = "Symbols of Unending Life" },
{ entry = 495, name = "Battlegear of Unyielding Strength" },
{ entry = 496, name = "Conqueror's Battlegear" },
{ entry = 497, name = "Deathdealer's Embrace" },
{ entry = 498, name = "Emblems of Veiled Shadows" },
{ entry = 499, name = "Doomcaller's Attire" },
{ entry = 500, name = "Implements of Unspoken Names" },
{ entry = 501, name = "Stormcaller's Garb" },
{ entry = 502, name = "Gift of the Gathering Storm" },
{ entry = 503, name = "Enigma Vestments" },
{ entry = 504, name = "Trappings of Vaulted Secrets" },
{ entry = 505, name = "Avenger's Battlegear" },
{ entry = 506, name = "Battlegear of Eternal Justice" },
{ entry = 507, name = "Garments of the Oracle" },
{ entry = 508, name = "Finery of Infinite Wisdom" },
{ entry = 509, name = "Striker's Garb" },
{ entry = 510, name = "Trappings of the Unseen Path" },
{ entry = 511, name = "Battlegear of Heroism" },
{ entry = 512, name = "Darkmantle Armor" },
{ entry = 513, name = "Feralheart Raiment" },
{ entry = 514, name = "Vestments of the Virtuous" },
{ entry = 515, name = "Beastmaster Armor" },
{ entry = 516, name = "Soulforge Armor" },
{ entry = 517, name = "Sorcerer's Regalia" },
{ entry = 518, name = "Deathmist Raiment" },
{ entry = 519, name = "The Five Thunders" },
{ entry = 520, name = "Ironweave Battlesuit" },
{ entry = 521, name = "Dreamwalker Raiment" },
{ entry = 522, name = "Champion's Guard" },
{ entry = 523, name = "Dreadnaught's Battlegear" },
{ entry = 524, name = "Bonescythe Armor" },
{ entry = 525, name = "Vestments of Faith" },
{ entry = 526, name = "Frostfire Regalia" },
{ entry = 527, name = "The Earthshatterer" },
{ entry = 528, name = "Redemption Armor" },
{ entry = 529, name = "Plagueheart Raiment" },
{ entry = 530, name = "Cryptstalker Armor" },
{ entry = 533, name = "Battlegear of Undead Slaying" },
{ entry = 534, name = "Undead Slayer's Armor" },
{ entry = 535, name = "Garb of the Undead Slayer" },
{ entry = 536, name = "Regalia of Undead Cleansing" },
{ entry = 537, name = "Champion's Battlearmor" },
{ entry = 538, name = "Champion's Stormcaller" },
{ entry = 539, name = "Champion's Refuge" },
{ entry = 540, name = "Champion's Investiture" },
{ entry = 541, name = "Champion's Dreadgear" },
{ entry = 542, name = "Champion's Arcanum" },
{ entry = 543, name = "Champion's Pursuance" },
{ entry = 544, name = "Lieutenant Commander's Redoubt" },
{ entry = 545, name = "Lieutenant Commander's Battlearmor" },
{ entry = 546, name = "Lieutenant Commander's Arcanum" },
{ entry = 547, name = "Lieutenant Commander's Dreadgear" },
{ entry = 548, name = "Lieutenant Commander's Guard" },
{ entry = 549, name = "Lieutenant Commander's Investiture" },
{ entry = 550, name = "Lieutenant Commander's Pursuance" },
{ entry = 551, name = "Lieutenant Commander's Refuge" },
{ entry = 552, name = "Wrath of Spellfire" },
{ entry = 553, name = "Shadow's Embrace" },
{ entry = 554, name = "Primal Mooncloth" },
{ entry = 555, name = "Netherweave Vestments" },
{ entry = 556, name = "Imbued Netherweave" },
{ entry = 557, name = "Soulcloth Embrace" },
{ entry = 558, name = "Arcanoweave Vestments" },
{ entry = 559, name = "Spellstrike Infusion" },
{ entry = 560, name = "Fel Iron Plate" },
{ entry = 561, name = "Fel Iron Chain" },
{ entry = 562, name = "Adamantite Battlegear" },
{ entry = 563, name = "Enchanted Adamantite Armor" },
{ entry = 564, name = "Flame Guard" },
{ entry = 565, name = "Khorium Ward" },
{ entry = 566, name = "Burning Rage" },
{ entry = 567, name = "Gladiator's Battlegear" },
{ entry = 568, name = "Gladiator's Dreadgear" },
{ entry = 569, name = "Faith in Felsteel" },
{ entry = 570, name = "The Unyielding" },
{ entry = 571, name = "Whitemend Wisdom" },
{ entry = 572, name = "Battlecast Garb" },
{ entry = 573, name = "Fel Skin" },
{ entry = 574, name = "Strength of the Clefthoof" },
{ entry = 575, name = "Felstalker Armor" },
{ entry = 576, name = "Fury of the Nether" },
{ entry = 577, name = "Gladiator's Vestments" },
{ entry = 578, name = "Gladiator's Earthshaker" },
{ entry = 579, name = "Gladiator's Regalia" },
{ entry = 580, name = "Gladiator's Thunderfist" },
{ entry = 581, name = "Gladiator's Raiment" },
{ entry = 582, name = "Gladiator's Aegis" },
{ entry = 583, name = "Gladiator's Vindication" },
{ entry = 584, name = "Gladiator's Sanctuary" },
{ entry = 585, name = "Gladiator's Wildhide" },
{ entry = 586, name = "Gladiator's Pursuit" },
{ entry = 587, name = "High Warlord's Aegis" },
{ entry = 588, name = "High Warlord's Battlegear" },
{ entry = 589, name = "Grand Marshal's Aegis" },
{ entry = 590, name = "Grand Marshal's Battlegear" },
{ entry = 591, name = "Grand Marshal's Dreadgear" },
{ entry = 592, name = "High Warlord's Dreadgear" },
{ entry = 593, name = "Grand Marshal's Earthshaker" },
{ entry = 594, name = "High Warlord's Earthshaker" },
{ entry = 595, name = "Grand Marshal's Pursuit" },
{ entry = 596, name = "High Warlord's Pursuit" },
{ entry = 597, name = "Grand Marshal's Raiment" },
{ entry = 598, name = "High Warlord's Raiment" },
{ entry = 599, name = "Grand Marshal's Regalia" },
{ entry = 600, name = "High Warlord's Regalia" },
{ entry = 601, name = "Grand Marshal's Sanctuary" },
{ entry = 602, name = "High Warlord's Sanctuary" },
{ entry = 603, name = "Grand Marshal's Thunderfist" },
{ entry = 604, name = "High Warlord's Thunderfist" },
{ entry = 605, name = "Grand Marshal's Vestments" },
{ entry = 606, name = "High Warlord's Vestments" },
{ entry = 607, name = "Grand Marshal's Vindication" },
{ entry = 608, name = "High Warlord's Vindication" },
{ entry = 609, name = "Grand Marshal's Wildhide" },
{ entry = 610, name = "High Warlord's Wildhide" },
{ entry = 611, name = "Felscale Armor" },
{ entry = 612, name = "Scaled Draenic Armor" },
{ entry = 613, name = "Thick Draenic Armor" },
{ entry = 614, name = "Wild Draenish Armor" },
{ entry = 615, name = "Gladiator's Felshroud" },
{ entry = 616, name = "Netherscale Armor" },
{ entry = 617, name = "Netherstrike Armor" },
{ entry = 618, name = "Windhawk Armor" },
{ entry = 619, name = "Primal Intent" },
{ entry = 620, name = "Assassination Armor" },
{ entry = 621, name = Netherblade },
{ entry = 622, name = Deathmantle },
{ entry = 623, name = "Righteous Armor" },
{ entry = 624, name = "Justicar Raiment" },
{ entry = 625, name = "Justicar Armor" },
{ entry = 626, name = "Justicar Battlegear" },
{ entry = 627, name = "Crystalforge Raiment" },
{ entry = 628, name = "Crystalforge Armor" },
{ entry = 629, name = "Crystalforge Battlegear" },
{ entry = 630, name = "Tidefury Raiment" },
{ entry = 631, name = "Cyclone Raiment" },
{ entry = 632, name = "Cyclone Regalia" },
{ entry = 633, name = "Cyclone Harness" },
{ entry = 634, name = "Cataclysm Raiment" },
{ entry = 635, name = "Cataclysm Regalia" },
{ entry = 636, name = "Cataclysm Harness" },
{ entry = 637, name = "Moonglade Raiment" },
{ entry = 638, name = "Malorne Raiment" },
{ entry = 639, name = "Malorne Regalia" },
{ entry = 640, name = "Malorne Harness" },
{ entry = 641, name = "Nordrassil Harness" },
{ entry = 642, name = "Nordrassil Raiment" },
{ entry = 643, name = "Nordrassil Regalia" },
{ entry = 644, name = "Oblivion Raiment" },
{ entry = 645, name = "Voidheart Raiment" },
{ entry = 646, name = "Corruptor Raiment" },
{ entry = 647, name = "Incanter's Regalia" },
{ entry = 648, name = "Aldor Regalia" },
{ entry = 649, name = "Tirisfal Regalia" },
{ entry = 650, name = "Beast Lord Armor" },
{ entry = 651, name = "Demon Stalker Armor" },
{ entry = 652, name = "Rift Stalker Armor" },
{ entry = 653, name = "Bold Armor" },
{ entry = 654, name = "Warbringer Armor" },
{ entry = 655, name = "Warbringer Battlegear" },
{ entry = 656, name = "Destroyer Armor" },
{ entry = 657, name = "Destroyer Battlegear" },
{ entry = 658, name = "Mana-Etched Regalia" },
{ entry = 659, name = "Wastewalker Armor" },
{ entry = 660, name = "Desolation Battlegear" },
{ entry = 661, name = "Doomplate Battlegear" },
{ entry = 662, name = "Hallowed Raiment" },
{ entry = 663, name = "Incarnate Raiment" },
{ entry = 664, name = "Incarnate Regalia" },
{ entry = 665, name = "Avatar Raiment" },
{ entry = 666, name = "Avatar Regalia" },
{ entry = 667, name = "The Twin Stars" },
{ entry = 668, name = "Slayer's Armor" },
{ entry = 669, name = "Gronnstalker's Armor" },
{ entry = 670, name = "Malefic Raiment" },
{ entry = 671, name = "Tempest Regalia" },
{ entry = 672, name = "Onslaught Battlegear" },
{ entry = 673, name = "Onslaught Armor" },
{ entry = 674, name = "Absolution Regalia" },
{ entry = 675, name = "Vestments of Absolution" },
{ entry = 676, name = "Thunderheart Harness" },
{ entry = 677, name = "Thunderheart Regalia" },
{ entry = 678, name = "Thunderheart Raiment" },
{ entry = 679, name = "Lightbringer Armor" },
{ entry = 680, name = "Lightbringer Battlegear" },
{ entry = 681, name = "Lightbringer Raiment" },
{ entry = 682, name = "Skyshatter Harness" },
{ entry = 683, name = "Skyshatter Raiment" },
{ entry = 684, name = "Skyshatter Regalia" },
{ entry = 685, name = "Gladiator's Refuge" },
{ entry = 686, name = "Gladiator's Wartide" },
{ entry = 687, name = "Gladiator's Investiture" },
{ entry = 688, name = "Grand Marshal's Refuge" },
{ entry = 689, name = "High Warlord's Refuge" },
{ entry = 690, name = "Gladiator's Redemption" },
{ entry = 691, name = "Grand Marshal's Investiture" },
{ entry = 692, name = "High Warlord's Investiture" },
{ entry = 693, name = "Grand Marshal's Redemption" },
{ entry = 694, name = "High Warlord's Redemption" },
{ entry = 695, name = "Grand Marshal's Wartide" },
{ entry = 696, name = "High Warlord's Wartide" },
{ entry = 697, name = "Champion's Redoubt" },
{ entry = 698, name = "Warlord's Aegis" },
{ entry = 699, name = "The Twin Blades of Azzinoth" },
{ entry = 700, name = "Merciless Gladiator's Aegis" },
{ entry = 701, name = "Merciless Gladiator's Battlegear" },
{ entry = 702, name = "Merciless Gladiator's Dreadgear" },
{ entry = 703, name = "Merciless Gladiator's Earthshaker" },
{ entry = 704, name = "Merciless Gladiator's Felshroud" },
{ entry = 705, name = "Merciless Gladiator's Investiture" },
{ entry = 706, name = "Merciless Gladiator's Pursuit" },
{ entry = 707, name = "Merciless Gladiator's Raiment" },
{ entry = 708, name = "Merciless Gladiator's Redemption" },
{ entry = 709, name = "Merciless Gladiator's Refuge" },
{ entry = 710, name = "Merciless Gladiator's Regalia" },
{ entry = 711, name = "Merciless Gladiator's Sanctuary" },
{ entry = 712, name = "Merciless Gladiator's Thunderfist" },
{ entry = 713, name = "Merciless Gladiator's Vestments" },
{ entry = 714, name = "Merciless Gladiator's Vindication" },
{ entry = 715, name = "Merciless Gladiator's Wartide" },
{ entry = 716, name = "Merciless Gladiator's Wildhide" },
{ entry = 717, name = "Field Marshal's Earthshaker" },
{ entry = 718, name = "Lieutenant Commander's Earthshaker" },
{ entry = 719, name = "The Fists of Fury" },
{ entry = 720, name = "Vengeful Gladiator's Refuge" },
{ entry = 721, name = "Vengeful Gladiator's Sanctuary" },
{ entry = 722, name = "Vengeful Gladiator's Wildhide" },
{ entry = 723, name = "Vengeful Gladiator's Pursuit" },
{ entry = 724, name = "Vengeful Gladiator's Regalia" },
{ entry = 725, name = "Vengeful Gladiator's Redemption" },
{ entry = 726, name = "Vengeful Gladiator's Vindication" },
{ entry = 727, name = "Vengeful Gladiator's Aegis" },
{ entry = 728, name = "Vengeful Gladiator's Investiture" },
{ entry = 729, name = "Vengeful Gladiator's Raiment" },
{ entry = 730, name = "Vengeful Gladiator's Vestments" },
{ entry = 731, name = "Vengeful Gladiator's Wartide" },
{ entry = 732, name = "Vengeful Gladiator's Earthshaker" },
{ entry = 733, name = "Vengeful Gladiator's Thunderfist" },
{ entry = 734, name = "Vengeful Gladiator's Dreadgear" },
{ entry = 735, name = "Vengeful Gladiator's Felshroud" },
{ entry = 736, name = "Vengeful Gladiator's Battlegear" },
{ entry = 737, name = "Latro's Flurry" },
{ entry = 738, name = "Dreadweave Battlegear" },
{ entry = 739, name = "Mooncloth Battlegear" },
{ entry = 740, name = "Satin Battlegear" },
{ entry = 741, name = "Evoker's Silk Battlegear" },
{ entry = 742, name = "Dragonhide Battlegear" },
{ entry = 743, name = "Wyrmhide Battlegear" },
{ entry = 744, name = "Kodohide Battlegear" },
{ entry = 745, name = "Opportunist's Battlegear" },
{ entry = 746, name = "Seer's Mail Battlegear" },
{ entry = 747, name = "Seer's Ringmail Battlegear" },
{ entry = 748, name = "Seer's Linked Battlegear" },
{ entry = 749, name = "Stalker's Chain Battlegear" },
{ entry = 750, name = "Savage Plate Battlegear" },
{ entry = 751, name = "Crusader's Ornamented Battlegear" },
{ entry = 752, name = "Crusader's Scaled Battlegear" },
{ entry = 754, name = "Borean Embrace" },
{ entry = 755, name = "Nerubian Hive" },
{ entry = 756, name = "Frostscale Binding" },
{ entry = 757, name = "Iceborne Embrace" },
{ entry = 759, name = "Raine's Revenge" },
{ entry = 760, name = "Gladiator's Dreadplate" },
{ entry = 761, name = "Winter Garb" },
{ entry = 762, name = "Brewfest Garb" },
{ entry = 763, name = "Frostwoven Power" },
{ entry = 764, name = Duskweaver },
{ entry = 765, name = "Gladiator's Battlegear" },
{ entry = 766, name = "Gladiator's Vindication" },
{ entry = 767, name = "Gladiator's Redemption" },
{ entry = 768, name = "Gladiator's Desecration" },
{ entry = 769, name = "Gladiator's Thunderfist" },
{ entry = 770, name = "Gladiator's Earthshaker" },
{ entry = 771, name = "Gladiator's Wartide" },
{ entry = 772, name = "Gladiator's Pursuit" },
{ entry = 773, name = "Gladiator's Refuge" },
{ entry = 774, name = "Gladiator's Wildhide" },
{ entry = 775, name = "Gladiator's Sanctuary" },
{ entry = 776, name = "Gladiator's Vestments" },
{ entry = 777, name = "Gladiator's Investiture" },
{ entry = 778, name = "Gladiator's Raiment" },
{ entry = 779, name = "Gladiator's Regalia" },
{ entry = 780, name = "Gladiator's Felshroud" },
{ entry = 781, name = "Blessed Regalia of Undead Cleansing" },
{ entry = 782, name = "Undead Slayer's Blessed Armor" },
{ entry = 783, name = "Blessed Garb of the Undead Slayer" },
{ entry = 784, name = "Blessed Battlegear of Undead Slaying" },
{ entry = 785, name = "Midsummer Reveler" },
{ entry = 787, name = "Dreadnaught Plate" },
{ entry = 788, name = "Dreadnaught Battlegear" },
{ entry = 789, name = "Redemption Battlegear" },
{ entry = 790, name = "Redemption Regalia" },
{ entry = 791, name = "Redemption Plate" },
{ entry = 792, name = "Scourgeborne Battlegear" },
{ entry = 793, name = "Scourgeborne Plate" },
{ entry = 794, name = "Cryptstalker Battlegear" },
{ entry = 795, name = "Earthshatter Battlegear" },
{ entry = 796, name = "Earthshatter Garb" },
{ entry = 797, name = "Earthshatter Regalia" },
{ entry = 798, name = "Dreamwalker Battlegear" },
{ entry = 799, name = "Dreamwalker Regalia" },
{ entry = 800, name = "Dreamwalker Garb" },
{ entry = 801, name = "Bonescythe Battlegear" },
{ entry = 802, name = "Plagueheart Garb" },
{ entry = 803, name = "Frostfire Garb" },
{ entry = 804, name = "Regalia of Faith" },
{ entry = 805, name = "Garb of Faith" },
{ entry = 812, name = "Spring Tuxedo" },
{ entry = 813, name = "Eviscerator's Battlegear" },
{ entry = 814, name = "Ornate Saronite Battlegear" },
{ entry = 815, name = "Overcaster Battlegear" },
{ entry = 816, name = "Savage Saronite Battlegear" },
{ entry = 817, name = "Stormhide Battlegear" },
{ entry = 818, name = "Swiftarrow Battlegear" },
{ entry = 819, name = "Frostsavage Battlegear" },
{ entry = 820, name = "Aegis Battlegear" },
{ entry = 821, name = "Aegis Plate" },
{ entry = 822, name = "Aegis Regalia" },
{ entry = 823, name = "Worldbreaker Battlegear" },
{ entry = 824, name = "Worldbreaker Garb" },
{ entry = 825, name = "Worldbreaker Regalia" },
{ entry = 826, name = "Terrorblade Battlegear" },
{ entry = 827, name = "Nightsong Battlegear" },
{ entry = 828, name = "Nightsong Garb" },
{ entry = 829, name = "Nightsong Regalia" },
{ entry = 830, name = "Siegebreaker Battlegear" },
{ entry = 831, name = "Siegebreaker Plate" },
{ entry = 832, name = "Sanctification Garb" },
{ entry = 833, name = "Sanctification Regalia" },
{ entry = 834, name = "Darkruned Battlegear" },
{ entry = 835, name = "Darkruned Plate" },
{ entry = 836, name = "Kirin Tor Garb" },
{ entry = 837, name = "Deathbringer Garb" },
{ entry = 838, name = "Scourgestalker Battlegear" },
{ entry = 842, name = "Awesome Party Ensemble" },
{ entry = 843, name = "Khadgar's Regalia" },
{ entry = 844, name = "Sunstrider's Regalia" },
{ entry = 845, name = "Gul'dan's Regalia" },
{ entry = 846, name = "Kel'Thuzad's Regalia" },
{ entry = 847, name = "Velen's Raiment" },
{ entry = 848, name = "Zabra's Raiment" },
{ entry = 849, name = "Velen's Regalia" },
{ entry = 850, name = "Zabra's Regalia" },
{ entry = 851, name = "Malfurion's Garb" },
{ entry = 852, name = "Runetotem's Garb" },
{ entry = 853, name = "Malfurion's Regalia" },
{ entry = 854, name = "Runetotem's Regalia" },
{ entry = 855, name = "Malfurion's Battlegear" },
{ entry = 856, name = "Runetotem's Battlegear" },
{ entry = 857, name = "VanCleef's Battlegear" },
{ entry = 858, name = "Garona's Battlegear" },
{ entry = 859, name = "Windrunner's Battlegear" },
{ entry = 860, name = "Windrunner's Pursuit" },
{ entry = 861, name = "Nobundo's Garb" },
{ entry = 862, name = "Thrall's Garb" },
{ entry = 863, name = "Thrall's Regalia" },
{ entry = 864, name = "Nobundo's Regalia" },
{ entry = 865, name = "Nobundo's Battlegear" },
{ entry = 866, name = "Thrall's Battlegear" },
{ entry = 867, name = "Wrynn's Battlegear" },
{ entry = 868, name = "Hellscream's Battlegear" },
{ entry = 869, name = "Wrynn's Plate" },
{ entry = 870, name = "Hellscream's Plate" },
{ entry = 871, name = "Thassarian's Battlegear" },
{ entry = 872, name = "Koltira's Battlegear" },
{ entry = 873, name = "Thassarian's Plate" },
{ entry = 874, name = "Koltira's Plate" },
{ entry = 875, name = "Turalyon's Garb" },
{ entry = 876, name = "Liadrin's Garb" },
{ entry = 877, name = "Turalyon's Battlegear" },
{ entry = 878, name = "Liadrin's Battlegear" },
{ entry = 879, name = "Turalyon's Plate" },
{ entry = 880, name = "Liadrin's Plate" },
{ entry = 881, name = "Purified Shard of the Gods" },
{ entry = 882, name = "Shiny Shard of the Gods" },
{ entry = 883, name = "Bloodmage's Regalia" },
{ entry = 884, name = "Dark Coven's Regalia" },
{ entry = 885, name = "Crimson Acolyte's Raiment" },
{ entry = 886, name = "Crimson Acolyte's Regalia" },
{ entry = 887, name = "Lasherweave Garb" },
{ entry = 888, name = "Lasherweave Regalia" },
{ entry = 889, name = "Lasherweave Battlegear" },
{ entry = 890, name = "Shadowblade's Battlegear" },
{ entry = 891, name = "Ahn'Kahar Blood Hunter's Battlegear" },
{ entry = 892, name = "Frost Witch's Garb" },
{ entry = 893, name = "Frost Witch's Regalia" },
{ entry = 894, name = "Frost Witch's Battlegear" },
{ entry = 895, name = "Ymirjar Lord's Battlegear" },
{ entry = 896, name = "Ymirjar Lord's Plate" },
{ entry = 897, name = "Scourgelord's Battlegear" },
{ entry = 898, name = "Scourgelord's Plate" },
{ entry = 899, name = "Lightsworn Garb" },
{ entry = 900, name = "Lightsworn Battlegear" },
{ entry = 901, name = "Lightsworn Plate" },
{ entry = 908, name = "The Defiler's Resolve" },
{ entry = 909, name = "Gladiator's Battlegear" },
{ entry = 910, name = "Gladiator's Felshroud" },
{ entry = 911, name = "Gladiator's Thunderfist" },
{ entry = 912, name = "Gladiator's Earthshaker" },
{ entry = 913, name = "Gladiator's Wartide" },
{ entry = 914, name = "Gladiator's Vestments" },
{ entry = 915, name = "Gladiator's Raiment" },
{ entry = 916, name = "Gladiator's Investiture" },
{ entry = 917, name = "Gladiator's Vindication" },
{ entry = 918, name = "Gladiator's Redemption" },
{ entry = 919, name = "Gladiator's Regalia" },
{ entry = 920, name = "Gladiator's Pursuit" },
{ entry = 921, name = "Gladiator's Wildhide" },
{ entry = 922, name = "Gladiator's Sanctuary" },
{ entry = 923, name = "Gladiator's Refuge" },
{ entry = 924, name = "Gladiator's Desecration" },
{ entry = 925, name = "Magma Plated Battlegear" },
{ entry = 926, name = "Magma Plated Battlearmor" },
{ entry = 927, name = "Stormrider's Battlegarb" },
{ entry = 928, name = "Stormrider's Vestments" },
{ entry = 929, name = "Stormrider's Regalia" },
{ entry = 930, name = "Lightning-Charged Battlegear" },
{ entry = 931, name = "Firelord's Vestments" },
{ entry = 932, name = "Reinforced Sapphirium Battleplate" },
{ entry = 933, name = "Reinforced Sapphirium Regalia" },
{ entry = 934, name = "Reinforced Sapphirium Battlearmor" },
{ entry = 935, name = "Mercurial Vestments" },
{ entry = 936, name = "Mercurial Regalia" },
{ entry = 937, name = "Wind Dancer's Regalia" },
{ entry = 938, name = "Vestments of the Raging Elements" },
{ entry = 939, name = "Battlegear of the Raging Elements" },
{ entry = 940, name = "Regalia of the Raging Elements" },
{ entry = 941, name = "Shadowflame Regalia" },
{ entry = 942, name = "Earthen Warplate" },
{ entry = 943, name = "Earthen Battleplate" },
{ entry = 944, name = Spiritmender },
{ entry = 945, name = Deathspeaker },
{ entry = 949, name = "The Dark Brand" },
{ entry = 950, name = "The Big Wave" },
{ entry = 951, name = "Agony and Torment" },
{ entry = 963, name = "Bloodthirsty Pyrium" },
{ entry = 964, name = "Bloodthirsty Ornate Pyrium" },
{ entry = 965, name = "Bloodthirsty Leather" },
{ entry = 966, name = "Bloodthirsty Wyrmhide" },
{ entry = 967, name = "Bloodthirsty Dragonscale" },
{ entry = 968, name = "Bloodthirsty Charscale" },
{ entry = 969, name = "Bloodthirsty Embersilk" },
{ entry = 970, name = "Bloodthirsty Fireweave" },
{ entry = 1000, name = "Elementium Deathplate Battlegear" },
{ entry = 1001, name = "Elementium Deathplate Battlearmor" },
{ entry = 1002, name = "Obsidian Arborweave Battlegarb" },
{ entry = 1003, name = "Obsidian Arborweave Regalia" },
{ entry = 1004, name = "Obsidian Arborweave Vestments" },
{ entry = 1005, name = "Flamewaker's Battlegear" },
{ entry = 1006, name = "Vestments of the Dark Phoenix" },
{ entry = 1007, name = "Firehawk Robes of Conflagration" },
{ entry = 1008, name = "Balespider's Burning Vestments" },
{ entry = 1009, name = "Vestments of the Cleansing Flame" },
{ entry = 1010, name = "Regalia of the Cleansing Flame" },
{ entry = 1011, name = "Regalia of Immolation" },
{ entry = 1012, name = "Battleplate of Immolation" },
{ entry = 1013, name = "Battlearmor of Immolation" },
{ entry = 1014, name = "Volcanic Vestments" },
{ entry = 1015, name = "Volcanic Battlegear" },
{ entry = 1016, name = "Volcanic Regalia" },
{ entry = 1017, name = "Molten Giant Warplate" },
{ entry = 1018, name = "Molten Giant Battleplate" },
{ entry = 1056, name = "Necrotic Boneplate Armor" },
{ entry = 1057, name = "Necrotic Boneplate Battlegear" },
{ entry = 1058, name = "Deep Earth Battlegarb" },
{ entry = 1059, name = "Deep Earth Regalia" },
{ entry = 1060, name = "Deep Earth Vestments" },
{ entry = 1061, name = "Wyrmstalker Battlegear" },
{ entry = 1062, name = "Time Lord's Regalia" },
{ entry = 1063, name = "Regalia of Radiant Glory" },
{ entry = 1064, name = "Battleplate of Radiant Glory" },
{ entry = 1065, name = "Armor of Radiant Glory" },
{ entry = 1066, name = "Vestments of Dying Light" },
{ entry = 1067, name = "Regalia of Dying Light" },
{ entry = 1068, name = "Blackfang Battleweave" },
{ entry = 1069, name = "Spiritwalker's Vestments" },
{ entry = 1070, name = "Spiritwalker's Regalia" },
{ entry = 1071, name = "Spiritwalker's Battlegear" },
{ entry = 1072, name = "Vestments of the Faceless Shroud" },
{ entry = 1073, name = "Colossal Dragonplate Battlegear" },
{ entry = 1074, name = "Colossal Dragonplate Armor" },
{ entry = 1087, name = "Fangs of the Father" },
{ entry = 1088, name = "Maw of Oblivion" },
{ entry = 1089, name = "Jaws of Retribution" },
{ entry = 1104, name = "Gladiator's Desecration" },
{ entry = 1105, name = "Gladiator's Refuge" },
{ entry = 1106, name = "Gladiator's Sanctuary" },
{ entry = 1107, name = "Gladiator's Wildhide" },
{ entry = 1108, name = "Gladiator's Pursuit" },
{ entry = 1109, name = "Gladiator's Regalia" },
{ entry = 1110, name = "Gladiator's Redemption" },
{ entry = 1111, name = "Gladiator's Vindication" },
{ entry = 1112, name = "Gladiator's Investiture" },
{ entry = 1113, name = "Gladiator's Vestments" },
{ entry = 1114, name = "Gladiator's Wartide" },
{ entry = 1115, name = "Gladiator's Earthshaker" },
{ entry = 1116, name = "Gladiator's Thunderfist" },
{ entry = 1117, name = "Gladiator's Felshroud" },
{ entry = 1118, name = "Gladiator's Battlegear" },
{ entry = 1119, name = "Gladiator's Copperskin" },
{ entry = 1120, name = "Gladiator's Ironskin" },
{ entry = 1121, name = "Contender's Defense" },
{ entry = 1123, name = "Battlegear of the Lost Catacomb" },
{ entry = 1124, name = "Plate of the Lost Catacomb" },
{ entry = 1125, name = "Vestments of the Eternal Blossom" },
{ entry = 1126, name = "Regalia of the Eternal Blossom" },
{ entry = 1127, name = "Battlegear of the Eternal Blossom" },
{ entry = 1128, name = "Armor of the Eternal Blossom" },
{ entry = 1129, name = "Yaungol Slayer Battlegear" },
{ entry = 1130, name = "Regalia of the Burning Scroll" },
{ entry = 1131, name = "Vestments of the Red Crane" },
{ entry = 1132, name = "Battlegear of the Red Crane" },
{ entry = 1133, name = "Armor of the Red Crane" },
{ entry = 1134, name = "White Tiger Vestments" },
{ entry = 1135, name = "White Tiger Battlegear" },
{ entry = 1136, name = "White Tiger Plate" },
{ entry = 1137, name = "Vestments of the Guardian Serpent" },
{ entry = 1138, name = "Regalia of the Guardian Serpent" },
{ entry = 1139, name = "Battlegear of the Thousandfold Blades" },
{ entry = 1140, name = "Vestments of the Firebird" },
{ entry = 1141, name = "Regalia of the Firebird" },
{ entry = 1142, name = "Battlegear of the Firebird" },
{ entry = 1143, name = "Sha-Skin Regalia" },
{ entry = 1144, name = "Battleplate of Resounding Rings" },
{ entry = 1145, name = "Plate of Resounding Rings" },
{ entry = 1146, name = "Gladiator's Raiment" },
{ entry = 1147, name = "Tradition of Cooking" },
{ entry = 1151, name = "Plate of the All-Consuming Maw" },
{ entry = 1152, name = "Battleplate of the All-Consuming Maw" },
{ entry = 1153, name = "Battlegear of the Haunted Forest" },
{ entry = 1154, name = "Vestments of the Haunted Forest" },
{ entry = 1155, name = "Regalia of the Haunted Forest" },
{ entry = 1156, name = "Armor of the Haunted Forest" },
{ entry = 1157, name = "Battlegear of the Saurok Stalker" },
{ entry = 1158, name = "Regalia of the Chromatic Hydra" },
{ entry = 1159, name = "Fire-Charm Battlegear" },
{ entry = 1160, name = "Fire-Charm Vestments" },
{ entry = 1161, name = "Fire-Charm Armor" },
{ entry = 1162, name = "Battlegear of the Lightning Emperor" },
{ entry = 1163, name = "Vestments of the Lightning Emperor" },
{ entry = 1164, name = "Plate of the Lightning Emperor" },
{ entry = 1165, name = "Vestments of the Exorcist" },
{ entry = 1166, name = "Regalia of the Exorcist" },
{ entry = 1167, name = "Nine-Tail Battlegear" },
{ entry = 1168, name = "Vestments of the Witch Doctor" },
{ entry = 1169, name = "Battlegear of the Witch Doctor" },
{ entry = 1170, name = "Regalia of the Witch Doctor" },
{ entry = 1171, name = "Regalia of the Thousandfold Hells" },
{ entry = 1172, name = "Battleplate of the Last Mogu" },
{ entry = 1173, name = "Plate of the Last Mogu" },
{ entry = 1179, name = "Plate of the Prehistoric Marauder" },
{ entry = 1180, name = "Battleplate of the Prehistoric Marauder" },
{ entry = 1181, name = "Regalia of the Horned Nightmare" },
{ entry = 1182, name = "Celestial Harmony Regalia" },
{ entry = 1183, name = "Celestial Harmony Battlegear" },
{ entry = 1184, name = "Celestial Harmony Vestment" },
{ entry = 1185, name = "Barbed Assassin Battlegear" },
{ entry = 1186, name = "Regalia of Ternion Glory" },
{ entry = 1187, name = "Vestments of Ternion Glory" },
{ entry = 1188, name = "Plate of Winged Triumph" },
{ entry = 1189, name = "Vestments of Winged Triumph" },
{ entry = 1190, name = "Battlegear of Winged Triumph" },
{ entry = 1191, name = "Armor of Seven Sacred Seals" },
{ entry = 1192, name = "Vestments of Seven Sacred Seals" },
{ entry = 1193, name = "Battlegear of Seven Sacred Seals" },
{ entry = 1194, name = "Chronomancer Regalia" },
{ entry = 1195, name = "Battlegear of the Unblinking Vigil" },
{ entry = 1196, name = "Armor of the Shattered Vale" },
{ entry = 1197, name = "Regalia of the Shattered Vale" },
{ entry = 1198, name = "Vestments of the Shattered Vale" },
{ entry = 1199, name = "Battlegear of the Shattered Vale" },
{ entry = 1200, name = "Battleplate of Cyclopean Dread" },
{ entry = 1201, name = "Plate of Cyclopean Dread" },
{ entry = 1203, name = "Gladiator's Distinction" },
{ entry = 1219, name = "6.0 test set" },
{ entry = 1220, name = "Gladiator's Desecration" },
{ entry = 1221, name = "Gladiator's Sanctuary" },
{ entry = 1222, name = "Gladiator's Pursuit" },
{ entry = 1223, name = "Gladiator's Regalia" },
{ entry = 1224, name = "Gladiator's Ironskin" },
{ entry = 1225, name = "Gladiator's Vindication" },
{ entry = 1226, name = "Gladiator's Investiture" },
{ entry = 1227, name = "Gladiator's Vestments" },
{ entry = 1228, name = "Gladiator's Wartide" },
{ entry = 1229, name = "Gladiator's Felshroud" },
{ entry = 1230, name = "Gladiator's Battlegear" },
{ entry = 1231, name = "Gladiator's Distinction" },
{ entry = 1233, name = "Living Wood Battlegear" },
{ entry = 1234, name = "Ogreskull Boneplate Battlegear" },
{ entry = 1235, name = "Arcanoshatter Regalia" },
{ entry = 1236, name = "Rylakstalker's Battlegear" },
{ entry = 1237, name = "Battlegear of the Somber Gaze" },
{ entry = 1238, name = "Battlegear of Guiding Light" },
{ entry = 1239, name = "Soul Priest's Raiment" },
{ entry = 1240, name = "Poisoner's Battlegear" },
{ entry = 1241, name = "Windspeaker's Regalia" },
{ entry = 1242, name = "Blackhand's Battlegear" },
{ entry = 1243, name = "Shadow Council's Garb" },
{ entry = 1244, name = "Might of the Warsong" },
{ entry = 1245, name = "Blacksteel Battleplate" },
{ entry = 1246, name = "Ashlink Armor" },
{ entry = 1247, name = "Sootfur Garb" },
{ entry = 1248, name = "Ebonflame Raiment" },
{ entry = 1249, name = "Demongaze Armor" },
{ entry = 1250, name = "Oathclaw Wargarb" },
{ entry = 1251, name = "Raiment of the Arcanic Conclave" },
{ entry = 1252, name = "Battlewrap of the Hurricane's Eye" },
{ entry = 1253, name = "Battlegear of the Savage Hunt" },
{ entry = 1254, name = "Watch of the Ceaseless Vigil" },
{ entry = 1255, name = "Attire of Piety" },
{ entry = 1256, name = "Felblade Armor" },
{ entry = 1257, name = "Embrace of the Living Mountain" },
{ entry = 1258, name = "Battlegear of Iron Wrath" },
{ entry = 1259, name = "Deathrattle Regalia" },
{ entry = 1260, name = "Felfume Raiment" },
{ entry = 1261, name = "Ironpelt Armor" },
{ entry = 1262, name = "Rancorbite Battlegear" },
{ entry = 1263, name = "Demonbreaker Wargear" },
{ entry = 1265, name = "Test [do not translate]" },
{ entry = 1266, name = "Illidari Slayer" },
{ entry = 1267, name = "Fel Infusion" },
{ entry = 1268, name = "The Scale's Embrace" },
{ entry = 1269, name = "Deathlord's Battleplate" },
{ entry = 1270, name = "Battlegear of the Shattered Abyss" },
{ entry = 1271, name = "Dreamgrove Raiment" },
{ entry = 1272, name = "Guise of the Unseen Path" },
{ entry = 1273, name = "Vesture of Tirisgarde" },
{ entry = 1274, name = "Grandmaster's Finery" },
{ entry = 1275, name = "Battleplate of the Silver Hand" },
{ entry = 1276, name = "Regalia of the High Priest" },
{ entry = 1277, name = "Battlegear of the Uncrowned" },
{ entry = 1278, name = "Raiment of the Farseer" },
{ entry = 1279, name = "Vestments of the Black Harvest" },
{ entry = 1280, name = "Battlelord's Plate" },
{ entry = 1281, name = "Dreadwyrm Battleplate" },
{ entry = 1282, name = "Vestment of Second Sight" },
{ entry = 1283, name = "Garb of the Astral Warden" },
{ entry = 1284, name = "Eagletalon Battlegear" },
{ entry = 1285, name = "Regalia of Everburning Knowledge" },
{ entry = 1286, name = "Vestments of Enveloped Dissonance" },
{ entry = 1287, name = "Battleplate of the Highlord" },
{ entry = 1288, name = "Vestments of the Purifier" },
{ entry = 1289, name = "Doomblade Battlegear" },
{ entry = 1290, name = "Regalia of Shackled Elements" },
{ entry = 1291, name = "Legacy of Azj'Aqir" },
{ entry = 1292, name = "Warplate of the Obsidian Aspect" },
{ entry = 1293, name = "March of the Legion" },
{ entry = 1294, name = "Journey Through Time" },
{ entry = 1295, name = "Nightwell Arcanum" },
{ entry = 1296, name = "Jacin's Ruse" },
{ entry = 1297, name = "Traitor's Oath" },
{ entry = 1298, name = "Fortitude of the Nightborne" },
{ entry = 1299, name = "Burden of Power" },
{ entry = 1301, name = "Gravewarden Armaments" },
{ entry = 1302, name = "Demonbane Armor" },
{ entry = 1303, name = "Stormheart Raiment" },
{ entry = 1304, name = "Wildstalker Armor" },
{ entry = 1305, name = "Regalia of the Arcane Tempest" },
{ entry = 1306, name = "Xuen's Battlegear" },
{ entry = 1307, name = "Radiant Lightbringer Armor" },
{ entry = 1308, name = "Vestments of Blind Absolution" },
{ entry = 1309, name = "Fanged Slayer's Armor" },
{ entry = 1310, name = "Regalia of the Skybreaker" },
{ entry = 1311, name = "Diabolic Raiment" },
{ entry = 1312, name = "Titanic Onslaught Armor" },
{ entry = 1319, name = "Juggernaut Battlegear" },
{ entry = 1320, name = "Grim Inquisitor's Regalia" },
{ entry = 1321, name = "Garb of Venerated Spirits" },
{ entry = 1322, name = "Regalia of the Dashing Scoundrel" },
{ entry = 1323, name = "Gilded Seraph's Raiment" },
{ entry = 1324, name = "Light's Vanguard Battleplate" },
{ entry = 1325, name = "Chi-Ji's Battlegear" },
{ entry = 1326, name = "Runebound Regalia" },
{ entry = 1327, name = "Serpentstalker Guise" },
{ entry = 1328, name = "Bearmantle Battlegear" },
{ entry = 1329, name = "Felreaper Vestments" },
{ entry = 1330, name = "Dreadwake Armor" },
{ entry = 1331, name = "Velen's Lament" },
{ entry = 1332, name = "Umbra-Weaver's Portent" },
{ entry = 1333, name = "Tailwind Regalia" },
{ entry = 1334, name = "Sea Sisters' Cunning" },
{ entry = 1335, name = "Venombite Garb" },
{ entry = 1336, name = "Thundercrash Armor" },
{ entry = 1337, name = "Sandstorm Plate" },
{ entry = 1338, name = "Frenzied Battleplate" },
{ entry = 1439, name = "Waycrest Legacy" },
{ entry = 1440, name = "Brain Trust" },
{ entry = 1442, name = "Gift of the Loa" },
{ entry = 1443, name = "Keepsakes of the Resolute Commandant" },
{ entry = 1449, name = "Azshara's Garments" },
{ entry = 1452, name = "Titanic Empowerment" },
{ entry = 1454, name = "Hack and Gore" },
{ entry = 1455, name = "Regalia of Fabled Adventurers" },
{ entry = 1456, name = "The Mail Courier" },
{ entry = 1457, name = "Hack and Gore" },
{ entry = 1458, name = "Gladiator's Distinction" },
{ entry = 1459, name = "Vestments of the Selfless" },
{ entry = 1460, name = "Rationale of Maldraxxus" },
{ entry = 1461, name = "Faewoven Regalia" },
{ entry = 1462, name = "Soulbreaker's Ebony Vestments" },
{ entry = 1463, name = "Inscrutable Exile's Garb" },
{ entry = 1466, name = "Garb of the Selfless" },
{ entry = 1467, name = "Chain of the Selfless" },
{ entry = 1468, name = "Vestments of the Selfless" },
{ entry = 1475, name = "Guile of Maldraxxus" },
{ entry = 1476, name = "Alacrity of Maldraxxus" },
{ entry = 1477, name = "Authority of Maldraxxus" },
{ entry = 1478, name = "Oakheart Raiment" },
{ entry = 1479, name = "Runewarden's Guise" },
{ entry = 1480, name = "Queensguard Warbark" },
{ entry = 1481, name = "Ebony Death Shroud Armor" },
{ entry = 1482, name = "Fearstalker's Ebony Battlegear" },
{ entry = 1483, name = "Dread Sentinel's Ebony Battleplate" },
{ entry = 1496, name = "Soulblade Shadowhide" },
{ entry = 1497, name = "Godstalker's Battlegear" },
{ entry = 1498, name = "Luminous Chevalier's Gallantry" },
{ entry = 1499, name = "Theurgic Starspeaker's Regalia" },
{ entry = 1500, name = "The First Eidolon's Soulsteel" },
{ entry = 1501, name = "Mercurial Punisher's Painweave" },
{ entry = 1502, name = "Tapestry of the Fixed Stars" },
{ entry = 1503, name = "Erudite Occultist's Vestments" },
{ entry = 1504, name = "Garb of the Grand Upwelling" },
{ entry = 1505, name = "Habiliments of the Empyrean" },
{ entry = 1506, name = "Armaments of the Infinite Infantry" },
{ entry = 1507, name = "Shroud of the Demon Star" },
{ entry = 1508, name = "Ripped Secrets" },
{ entry = 1509, name = "Playful Spirit's Fur" },
{ entry = 1510, name = "Horizon Strider's Garments" },
{ entry = 1511, name = "Drakebreaker's Garb" },
{ entry = 1512, name = "Drakebreaker's Battlegear" },
{ entry = 1513, name = "Drakebreaker's Vestments" },
{ entry = 1514, name = "Drakebreaker's Armor" },
{ entry = 1515, name = "Woven Chronocloth" },
{ entry = 1516, name = "Azureweave Vestments" },
{ entry = 1520, name = "Dragon Rider's Gear" },
{ entry = 1521, name = "Drape of Raging Tempests" },
{ entry = 1523, name = "Shroud of Raging Tempests" },
{ entry = 1524, name = "Scales of Raging Tempests" },
{ entry = 1525, name = "Armor of Raging Tempests" },
{ entry = 1526, name = "Haunted Frostbrood Remains" },
{ entry = 1527, name = "Skybound Avenger's Flightwear" },
{ entry = 1528, name = "Lost Landcaller's Vesture" },
{ entry = 1529, name = "Stormwing Harrier's Camouflage" },
{ entry = 1530, name = "Scales of the Awakened" },
{ entry = 1531, name = "Bindings of the Crystal Scholar" },
{ entry = 1532, name = "Wrappings of the Waking Fist" },
{ entry = 1533, name = "Virtuous Silver Cataphract" },
{ entry = 1534, name = "Draconic Hierophant's Finery" },
{ entry = 1535, name = "Vault Delver's Toolkit" },
{ entry = 1536, name = "Elements of Infused Earth" },
{ entry = 1537, name = "Scalesworn Cultist's Habit" },
{ entry = 1538, name = "Stones of the Walking Mountain" },
{ entry = 1539, name = "Might of the Drogbar" },
{ entry = 1540, name = "Lingering Phantom's Encasement" },
{ entry = 1541, name = "Kinslayer's Burdens" },
{ entry = 1542, name = "Strands of the Autumn Blaze" },
{ entry = 1543, name = "Legacy of Obsidian Secrets" },
{ entry = 1544, name = "Ashen Predator's Scaleform" },
{ entry = 1545, name = "Underlight Conjurer's Brilliance" },
{ entry = 1546, name = "Fangs of the Vermillion Forge" },
{ entry = 1547, name = "Heartfire Sentinel's Authority" },
{ entry = 1548, name = "The Furnace Seraph's Verdict" },
{ entry = 1549, name = "Lurking Specter's Shadeweave" },
{ entry = 1550, name = "Runes of the Cinderwolf" },
{ entry = 1551, name = "Sinister Savant's Cursethreads" },
{ entry = 1552, name = "Irons of the Onyx Crucible" },
{ entry = 1553, name = "Scalewarden's Garments" },
{ entry = 1554, name = "Scalewarden's Chainmail" },
{ entry = 1555, name = "Scalewarden's Battlegear" },
{ entry = 1556, name = "Scalewarden's Armaments" },
{ entry = 1557, name = "Risen Nightmare's Gravemantle" },
{ entry = 1558, name = "Screaming Torchfiend's Brutality" },
{ entry = 1559, name = "Benevolent Embersage's Guidance" },
{ entry = 1560, name = "Werynkeeper's Timeless Vigil" },
{ entry = 1561, name = "Blazing Dreamstalker's Trophies" },
{ entry = 1562, name = "Wayward Chronomancer's Clockwork" },
{ entry = 1563, name = "Mystic Heron's Discipline" },
{ entry = 1564, name = "Zealous Pyreknight's Ardor" },
{ entry = 1565, name = "Blessings of Lunar Communion" },
{ entry = 1566, name = "Lucid Shadewalker's Silence" },
{ entry = 1567, name = "Vision of the Greatwolf Outcast" },
{ entry = 1568, name = "Devout Ashdevil's Pactweave" },
{ entry = 1569, name = "Molten Vanguard's Mortarplate" },
{ entry = 1572, name = "Hellbloom Armaments" },
{ entry = 1573, name = "Hellbloom Chainmail" },
{ entry = 1574, name = "Hellbloom Battlegear" },
{ entry = 1575, name = "Hellbloom Garments" },
{ entry = 1594, name = "Scales of the Awakened" },
{ entry = 1595, name = "Stormwing Harrier's Camouflage" },
{ entry = 1596, name = "Wrappings of the Waking Fist" },
{ entry = 1597, name = "Strands of the Autumn Blaze" },
{ entry = 1598, name = "Heartfire Sentinel's Authority" },
{ entry = 1599, name = "The Furnace Seraph's Verdict" },
{ entry = 1600, name = "Lurking Specter's Shadeweave" },
{ entry = 1601, name = "Sinister Savant's Cursethreads" },
{ entry = 1602, name = "Irons of the Onyx Crucible" },
{ entry = 1603, name = "Risen Nightmare's Gravemantle" },
{ entry = 1604, name = "Screaming Torchfiend's Brutality" },
{ entry = 1605, name = "Wayward Chronomancer's Clockwork" },
{ entry = 1606, name = "Vision of the Greatwolf Outcast" },
{ entry = 1611, name = "Embrace of the Cinderbee" },
{ entry = 1612, name = "Fury of the Stormrook" },
{ entry = 1613, name = "Ky'veza's Cruel Implements" },
{ entry = 1614, name = "Draconic Warmonger's Armor" },
{ entry = 1615, name = "Draconic Warmonger's Chainmail" },
{ entry = 1616, name = "Draconic Warmonger's Vestments" },
{ entry = 1617, name = "Draconic Warmonger's Garb" },
{ entry = 1683, name = "Woven Dawn" },
{ entry = 1684, name = "Warsculptor's Masterwork" },
{ entry = 1685, name = "Rites of the Hexflame Coven" },
{ entry = 1686, name = "Waves of the Forgotten Reservoir" },
{ entry = 1687, name = "K'areshi Phantom's Bindings" },
{ entry = 1688, name = "Shards of Living Luster" },
{ entry = 1689, name = "Entombed Seraph's Radiance" },
{ entry = 1690, name = "Gatecrasher's Fortitude" },
{ entry = 1691, name = "Sparks of Violet Rebirth" },
{ entry = 1692, name = "Lightless Scavenger's Necessities" },
{ entry = 1693, name = "Destroyer's Scarred Wards" },
{ entry = 1694, name = "Mane of the Greatlynx" },
{ entry = 1695, name = "Husk of the Hypogeal Nemesis" },
{ entry = 1696, name = "Exhumed Centurion's Relics" },
{ entry = 1697, name = "Woven Dusk" },
{ entry = 1834, name = "Lingering Dark Iron Grace" },
{ entry = 1867, name = "Cauldron Champion's Encore" },
{ entry = 1868, name = "Fel-Dealer's Contraband" },
{ entry = 1869, name = "Roots of Reclaiming Blight" },
{ entry = 1870, name = "Opulent Treasurescale's Hoard" },
{ entry = 1871, name = "Tireless Collector's Bounties" },
{ entry = 1872, name = "Jewels of the Aspectral Emissary" },
{ entry = 1873, name = "Ageless Serpent's Foresight" },
{ entry = 1874, name = "Oath of the Aureate Sentry" },
{ entry = 1875, name = "Confessor's Unshakable Virtue" },
{ entry = 1876, name = "Spectral Gambler's Last Call" },
{ entry = 1877, name = "Currents of the Gale Sovereign" },
{ entry = 1878, name = "Spliced Fiendtrader's Influence" },
{ entry = 1879, name = "Underpin Strongarm's Muscle" },

}