SkillsData = {
{ entry = 333, name = "Enchanting" },
{ entry = 202, name = "Engineering" },
{ entry = 164, name = "Blacksmithing" },
{ entry = 773, name = "Inscription" },
{ entry = 197, name = "Tailoring" },
{ entry = 755, name = "Jewelcrafting" },
{ entry = 165, name = "Leatherworking" },
{ entry = 171, name = "Alchemy" },
{ entry = 794, name = "Archaeology" },
{ entry = 182, name = "Herbalism" },
{ entry = 356, name = "Fishing" },
{ entry = 185, name = "Cooking" },
{ entry = 186, name = "Mining" },
{ entry = 762, name = "Riding" },
{ entry = 960, name = "Runeforging" },
{ entry = 393, name = "Skinning" },
{ entry = 2875, name = "Khaz Algar Engineering" },
{ entry = 2874, name = "Khaz Algar Enchanting" },
{ entry = 777, name = "Mounts" },
{ entry = 2871, name = "Khaz Algar Alchemy" },
{ entry = 2883, name = "Khaz Algar Tailoring" },
{ entry = 2528, name = "Pandaria Leatherworking" },
{ entry = 2872, name = "Khaz Algar Blacksmithing" },
{ entry = 2878, name = "Khaz Algar Inscription" },
{ entry = 2881, name = "Khaz Algar Mining" },
{ entry = 2880, name = "Khaz Algar Leatherworking" },
{ entry = 160, name = "Two-Handed Maces" },
{ entry = 2504, name = "Northrend Engineering" },
{ entry = 413, name = "Mail" },
{ entry = 2879, name = "Khaz Algar Jewelcrafting" },
{ entry = 2873, name = "Khaz Algar Cooking" },
{ entry = 2552, name = "Pandaria Herbalism" },
{ entry = 2720, name = "Junkyard Tinkering" },
{ entry = 2485, name = "Classic Alchemy" },
{ entry = 2506, name = "Classic Engineering" },
{ entry = 2882, name = "Khaz Algar Skinning" },
{ entry = 2734, name = "Mount Equipment" },
{ entry = 2876, name = "Khaz Algar Fishing" },
{ entry = 2877, name = "Khaz Algar Herbalism" },
{ entry = 54, name = "Maces" },
{ entry = 2505, name = "Outland Engineering" },
{ entry = 2568, name = "Pandaria Mining" },
{ entry = 2521, name = "Cataclysm Jewelcrafting" },
{ entry = 414, name = "Leather" },
{ entry = 293, name = "Plate Mail" },
{ entry = 904, name = "Mage" },
{ entry = 2727, name = "All Classes" },
{ entry = 46, name = "Guns" },
{ entry = 229, name = "Polearms" },
{ entry = 2833, name = "Dragon Isles Mining" },
{ entry = 2791, name = "Ascension Crafting" },
{ entry = 2825, name = "Dragon Isles Enchanting" },
{ entry = 921, name = "Rogue" },
{ entry = 2499, name = "Kul Tiran Engineering" },
{ entry = 473, name = "Fist Weapons" },
{ entry = 2152, name = "Warglaives" },
{ entry = 2566, name = "Legion Mining" },
{ entry = 2902, name = "All - Warbands" },
{ entry = 137, name = "Thalassian" },
{ entry = 829, name = "Monk" },
{ entry = 2503, name = "Cataclysm Engineering" },
{ entry = 98, name = "Common" },
{ entry = 415, name = "Cloth" },
{ entry = 924, name = "Shaman" },
{ entry = 2540, name = "Classic Tailoring" },
{ entry = 2542, name = "Legion Cooking" },
{ entry = 2567, name = "Draenor Mining" },
{ entry = 2730, name = "Kyrian" },
{ entry = 2500, name = "Legion Engineering" },
{ entry = 2553, name = "Cataclysm Herbalism" },
{ entry = 2831, name = "Dragon Isles Tailoring" },
{ entry = 2482, name = "Cataclysm Alchemy" },
{ entry = 172, name = "Two-Handed Axes" },
{ entry = 2477, name = "Classic Blacksmithing" },
{ entry = 2502, name = "Pandaria Engineering" },
{ entry = 2520, name = "Pandaria Jewelcrafting" },
{ entry = 2756, name = "Shadowlands Inscription" },
{ entry = 2481, name = "Pandaria Alchemy" },
{ entry = 173, name = "Daggers" },
{ entry = 930, name = "Observer" },
{ entry = 2544, name = "Pandaria Cooking" },
{ entry = 2571, name = "Outland Mining" },
{ entry = 43, name = "Swords" },
{ entry = 2570, name = "Northrend Mining" },
{ entry = 2588, name = "Pandaria Fishing" },
{ entry = 2829, name = "Dragon Isles Jewelcrafting" },
{ entry = 2847, name = "Tuskarr Fishing Gear" },
{ entry = 228, name = "Wands" },
{ entry = 1848, name = "Demon Hunter" },
{ entry = 2507, name = "Kul Tiran Inscription" },
{ entry = 2592, name = "Classic Fishing" },
{ entry = 136, name = "Staves" },
{ entry = 778, name = "Companions" },
{ entry = 2493, name = "Outland Enchanting" },
{ entry = 2510, name = "Pandaria Inscription" },
{ entry = 2546, name = "Northrend Cooking" },
{ entry = 2560, name = "Pandaria Skinning" },
{ entry = 2563, name = "Outland Skinning" },
{ entry = 2752, name = "Shadowlands Cooking" },
{ entry = 2819, name = "Protoform Synthesis" },
{ entry = 1945, name = "Logging" },
{ entry = 2486, name = "Kul Tiran Enchanting" },
{ entry = 2533, name = "Kul Tiran Tailoring" },
{ entry = 2564, name = "Classic Skinning" },
{ entry = 45, name = "Bows" },
{ entry = 840, name = "Warrior" },
{ entry = 2538, name = "Northrend Tailoring" },
{ entry = 2569, name = "Cataclysm Mining" },
{ entry = 2787, name = "Abominable Stitching" },
{ entry = 2551, name = "Draenor Herbalism" },
{ entry = 2830, name = "Dragon Isles Leatherworking" },
{ entry = 2846, name = "Crafting" },
{ entry = 55, name = "Two-Handed Swords" },
{ entry = 2480, name = "Draenor Alchemy" },
{ entry = 2513, name = "Outland Inscription" },
{ entry = 2562, name = "Northrend Skinning" },
{ entry = 226, name = "Crossbows" },
{ entry = 315, name = "Troll" },
{ entry = 2478, name = "Kul Tiran Alchemy" },
{ entry = 2484, name = "Outland Alchemy" },
{ entry = 2536, name = "Pandaria Tailoring" },
{ entry = 2555, name = "Outland Herbalism" },
{ entry = 2586, name = "Legion Fishing" },
{ entry = 2760, name = "Shadowlands Herbalism" },
{ entry = 2823, name = "Dragon Isles Alchemy" },
{ entry = 2476, name = "Outland Blacksmithing" },
{ entry = 2731, name = "Venthyr" },
{ entry = 2834, name = "Dragon Isles Skinning" },
{ entry = 2479, name = "Legion Alchemy" },
{ entry = 2488, name = "Draenor Enchanting" },
{ entry = 2494, name = "Classic Enchanting" },
{ entry = 2545, name = "Cataclysm Cooking" },
{ entry = 2816, name = "Adventurer" },
{ entry = 2828, name = "Dragon Isles Inscription" },
{ entry = 2437, name = "Kul Tiran Blacksmithing" },
{ entry = 2475, name = "Northrend Blacksmithing" },
{ entry = 2501, name = "Draenor Engineering" },
{ entry = 2522, name = "Northrend Jewelcrafting" },
{ entry = 2548, name = "Classic Cooking" },
{ entry = 2557, name = "Kul Tiran Skinning" },
{ entry = 2561, name = "Cataclysm Skinning" },
{ entry = 2585, name = "Kul Tiran Fishing" },
{ entry = 2591, name = "Outland Fishing" },
{ entry = 2705, name = "Pet - Exotic Pterrordax" },
{ entry = 2732, name = "Night Fae" },
{ entry = 2733, name = "Necrolord" },
{ entry = 2755, name = "Shadowlands Engineering" },
{ entry = 2757, name = "Shadowlands Jewelcrafting" },
{ entry = 2810, name = "Evoker" },
{ entry = 433, name = "Shield" },
{ entry = 2454, name = "Legion Blacksmithing" },
{ entry = 2537, name = "Cataclysm Tailoring" },
{ entry = 2822, name = "Dragon Isles Blacksmithing" },
{ entry = 2832, name = "Dragon Isles Herbalism" },
{ entry = 313, name = "Gnomish" },
{ entry = 2523, name = "Outland Jewelcrafting" },
{ entry = 2532, name = "Classic Leatherworking" },
{ entry = 2543, name = "Draenor Cooking" },
{ entry = 2549, name = "Kul Tiran Herbalism" },
{ entry = 2556, name = "Classic Herbalism" },
{ entry = 2590, name = "Northrend Fishing" },
{ entry = 2776, name = "Vulpera" },
{ entry = 2821, name = "Arcana Manipulation" },
{ entry = 2824, name = "Dragon Isles Cooking" },
{ entry = 44, name = "Axes" },
{ entry = 113, name = "Darnassian" },
{ entry = 2527, name = "Draenor Leatherworking" },
{ entry = 2539, name = "Outland Tailoring" },
{ entry = 2547, name = "Outland Cooking" },
{ entry = 2805, name = "Pet - Mammoth" },
{ entry = 2472, name = "Draenor Blacksmithing" },
{ entry = 2491, name = "Cataclysm Enchanting" },
{ entry = 2524, name = "Classic Jewelcrafting" },
{ entry = 2525, name = "Kul Tiran Leatherworking" },
{ entry = 2554, name = "Northrend Herbalism" },
{ entry = 2565, name = "Kul Tiran Mining" },
{ entry = 2572, name = "Classic Mining" },
{ entry = 2704, name = "Pet - Horse" },
{ entry = 2754, name = "Shadowlands Fishing" },
{ entry = 2758, name = "Shadowlands Leatherworking" },
{ entry = 2855, name = "Furbolg" },
{ entry = 2884, name = "Earthen" },
{ entry = 109, name = "Orcish" },
{ entry = 111, name = "Dwarven" },
{ entry = 791, name = "Gilnean" },
{ entry = 849, name = "Warlock" },
{ entry = 981, name = "Apprentice Cooking" },
{ entry = 2189, name = "Pet - Mechanical" },
{ entry = 2216, name = "Pet - Abomination" },
{ entry = 2279, name = "Pet - Oxen" },
{ entry = 2280, name = "Pet - Scalehide" },
{ entry = 2464, name = "Shalassian" },
{ entry = 2508, name = "Legion Inscription" },
{ entry = 2526, name = "Legion Leatherworking" },
{ entry = 2529, name = "Cataclysm Leatherworking" },
{ entry = 2530, name = "Northrend Leatherworking" },
{ entry = 2531, name = "Outland Leatherworking" },
{ entry = 2534, name = "Legion Tailoring" },
{ entry = 2535, name = "Draenor Tailoring" },
{ entry = 2558, name = "Legion Skinning" },
{ entry = 2587, name = "Draenor Fishing" },
{ entry = 2706, name = "Pet - Toad" },
{ entry = 2707, name = "Pet - Exotic Carapid" },
{ entry = 2716, name = "Second Pet - Hunter" },
{ entry = 2719, name = "Pet - Blood Beast" },
{ entry = 2751, name = "Shadowlands Blacksmithing" },
{ entry = 2753, name = "Shadowlands Enchanting" },
{ entry = 2759, name = "Shadowlands Tailoring" },
{ entry = 2761, name = "Shadowlands Mining" },
{ entry = 2762, name = "Shadowlands Skinning" },
{ entry = 2850, name = "Pet - Lesser Dragonkin" },
{ entry = 905, name = "Pandaren Neutral" },
{ entry = 2473, name = "Pandaria Blacksmithing" },
{ entry = 2511, name = "Cataclysm Inscription" },
{ entry = 2512, name = "Northrend Inscription" },
{ entry = 2517, name = "Kul Tiran Jewelcrafting" },
{ entry = 2519, name = "Draenor Jewelcrafting" },
{ entry = 2550, name = "Legion Herbalism" },
{ entry = 2559, name = "Draenor Skinning" },
{ entry = 2703, name = "Pet - Lizard" },
{ entry = 2817, name = "Cypher" },
{ entry = 2826, name = "Dragon Isles Fishing" },
{ entry = 2870, name = "Shipment Prototype" },
{ entry = 673, name = "Forsaken" },
{ entry = 759, name = "Draenei" },
{ entry = 792, name = "Goblin" },
{ entry = 1777, name = "Pet - Water Elemental Minor Talent Version" },
{ entry = 2361, name = "Pet - Feathermane" },
{ entry = 2465, name = "Thalassian" },
{ entry = 2474, name = "Cataclysm Blacksmithing" },
{ entry = 2483, name = "Northrend Alchemy" },
{ entry = 2489, name = "Pandaria Enchanting" },
{ entry = 2509, name = "Draenor Inscription" },
{ entry = 2514, name = "Classic Inscription" },
{ entry = 2541, name = "Kul Tiran Cooking" },
{ entry = 2589, name = "Cataclysm Fishing" },
{ entry = 2750, name = "Shadowlands Alchemy" },
{ entry = 2777, name = "Soul Cyphering" },
{ entry = 2806, name = "Pet - Courser" },
{ entry = 2807, name = "Pet - Camel" },
{ entry = 2827, name = "Dragon Isles Engineering" },
{ entry = 2886, name = "Supply Shipments" },
{ entry = 115, name = "Taurahe" },
{ entry = 934, name = "All - Specializations" },
{ entry = 2487, name = "Legion Enchanting" },
{ entry = 2492, name = "Northrend Enchanting" },
{ entry = 2518, name = "Legion Jewelcrafting" },
{ entry = 2811, name = "Stygia Crafting" },


}