TitlesData = {
{ entry = 1, name = "Private %s" },
{ entry = 2, name = "Corporal %s" },
{ entry = 3, name = "Sergeant %s" },
{ entry = 4, name = "Master Sergeant %s" },
{ entry = 5, name = "Sergeant Major %s" },
{ entry = 6, name = "Knight %s" },
{ entry = 7, name = "Knight-Lieutenant %s" },
{ entry = 8, name = "Knight-Captain %s" },
{ entry = 9, name = "Knight-Champion %s" },
{ entry = 10, name = "Lieutenant Commander %s" },
{ entry = 11, name = "Commander %s" },
{ entry = 12, name = "Marshal %s" },
{ entry = 13, name = "Field Marshal %s" },
{ entry = 14, name = "Grand Marshal %s" },
{ entry = 15, name = "Scout %s" },
{ entry = 16, name = "Grunt %s" },
{ entry = 17, name = "Sergeant %s" },
{ entry = 18, name = "Senior Sergeant %s" },
{ entry = 19, name = "First Sergeant %s" },
{ entry = 20, name = "Stone Guard %s" },
{ entry = 21, name = "Blood Guard %s" },
{ entry = 22, name = "Legionnaire %s" },
{ entry = 23, name = "Centurion %s" },
{ entry = 24, name = "Champion %s" },
{ entry = 25, name = "Lieutenant General %s" },
{ entry = 26, name = "General %s" },
{ entry = 27, name = "Warlord %s" },
{ entry = 28, name = "High Warlord %s" },
{ entry = 42, name = "Gladiator %s" },
{ entry = 43, name = "Duelist %s" },
{ entry = 44, name = "Rival %s" },
{ entry = 45, name = "Challenger %s" },
{ entry = 46, name = "Scarab Lord %s" },
{ entry = 47, name = "Conqueror %s" },
{ entry = 48, name = "Justicar %s" },
{ entry = 53, name = "%s, Champion of the Naaru" },
{ entry = 62, name = "Merciless Gladiator %s" },
{ entry = 63, name = "%s of the Shattered Sun" },
{ entry = 64, name = "%s, Hand of A'dal" },
{ entry = 71, name = "Vengeful Gladiator %s" },
{ entry = 72, name = "Battlemaster %s" },
{ entry = 74, name = "Elder %s" },
{ entry = 75, name = "Flame Warden %s" },
{ entry = 76, name = "Flame Keeper %s" },
{ entry = 77, name = "%s the Exalted" },
{ entry = 78, name = "%s the Explorer" },
{ entry = 79, name = "%s the Diplomat" },
{ entry = 80, name = "Brutal Gladiator %s" },
{ entry = 81, name = "%s the Seeker" },
{ entry = 82, name = "Arena Master %s" },
{ entry = 83, name = "Salty %s" },
{ entry = 84, name = "Chef %s" },
{ entry = 85, name = "Crashin' Thrashin' %s" },
{ entry = 86, name = "%s of the Ten Storms" },
{ entry = 87, name = "%s of the Emerald Dream" },
{ entry = 89, name = "Prophet %s" },
{ entry = 90, name = "%s the Malefic" },
{ entry = 91, name = "Predator %s" },
{ entry = 92, name = "%s of the Ebon Blade" },
{ entry = 93, name = "Archmage %s" },
{ entry = 94, name = "Battlelord %s" },
{ entry = 95, name = "Assassin %s" },
{ entry = 96, name = "Grand Master Alchemist %s" },
{ entry = 97, name = "Grand Master Blacksmith %s" },
{ entry = 98, name = "Iron Chef %s" },
{ entry = 99, name = "Grand Master Enchanter %s" },
{ entry = 100, name = "Grand Master Engineer %s" },
{ entry = 101, name = "Doctor %s" },
{ entry = 102, name = "Grand Master Angler %s" },
{ entry = 103, name = "Grand Master Herbalist %s" },
{ entry = 104, name = "Grand Master Scribe %s" },
{ entry = 105, name = "Grand Master Jewelcrafter %s" },
{ entry = 106, name = "Grand Master Leatherworker %s" },
{ entry = 107, name = "Grand Master Miner %s" },
{ entry = 108, name = "Grand Master Skinner %s" },
{ entry = 109, name = "Grand Master Tailor %s" },
{ entry = 110, name = "Combatant %s" },
{ entry = 111, name = "Dread Gladiator %s" },
{ entry = 112, name = "Sinister Gladiator %s" },
{ entry = 113, name = "%s of Gnomeregan" },
{ entry = 114, name = "%s the Lion Hearted" },
{ entry = 115, name = "%s, Champion of Elune" },
{ entry = 116, name = "%s, Hero of Orgrimmar" },
{ entry = 117, name = "Plainsrunner %s" },
{ entry = 118, name = "%s of the Darkspear" },
{ entry = 119, name = "%s the Forsaken" },
{ entry = 120, name = "%s the Magic Seeker" },
{ entry = 121, name = "Twilight Vanquisher %s" },
{ entry = 122, name = "%s, Conqueror of Naxxramas" },
{ entry = 123, name = "%s, Hero of Northrend" },
{ entry = 124, name = "%s the Hallowed" },
{ entry = 125, name = "Loremaster %s" },
{ entry = 126, name = "%s of the Alliance" },
{ entry = 127, name = "%s of the Horde" },
{ entry = 128, name = "%s the Flawless Victor" },
{ entry = 129, name = "%s, Champion of the Frozen Wastes" },
{ entry = 130, name = "Ambassador %s" },
{ entry = 131, name = "%s the Argent Champion" },
{ entry = 132, name = "%s, Guardian of Cenarius" },
{ entry = 133, name = "Brewmaster %s" },
{ entry = 134, name = "Merrymaker %s" },
{ entry = 135, name = "%s the Love Fool" },
{ entry = 137, name = "Matron %s" },
{ entry = 138, name = "Patron %s" },
{ entry = 139, name = "Obsidian Slayer %s" },
{ entry = 140, name = "%s of the Nightfall" },
{ entry = 141, name = "%s the Immortal" },
{ entry = 142, name = "%s the Undying" },
{ entry = 143, name = "%s Jenkins" },
{ entry = 144, name = "Bloodsail Admiral %s" },
{ entry = 145, name = "%s the Insane" },
{ entry = 146, name = "%s of the Exodar" },
{ entry = 147, name = "%s of Darnassus" },
{ entry = 148, name = "%s of Ironforge" },
{ entry = 149, name = "%s of Stormwind" },
{ entry = 150, name = "%s of Orgrimmar" },
{ entry = 151, name = "%s of Sen'jin" },
{ entry = 152, name = "%s of Silvermoon" },
{ entry = 153, name = "%s of Thunder Bluff" },
{ entry = 154, name = "%s of the Undercity" },
{ entry = 155, name = "%s the Noble" },
{ entry = 156, name = "Crusader %s" },
{ entry = 157, name = "Deadly Gladiator %s" },
{ entry = 158, name = "%s, Death's Demise" },
{ entry = 159, name = "%s the Celestial Defender" },
{ entry = 160, name = "%s, Conqueror of Ulduar" },
{ entry = 161, name = "%s, Champion of Ulduar" },
{ entry = 163, name = "Vanquisher %s" },
{ entry = 164, name = "Starcaller %s" },
{ entry = 165, name = "%s the Astral Walker" },
{ entry = 166, name = "%s, Herald of the Titans" },
{ entry = 167, name = "Furious Gladiator %s" },
{ entry = 168, name = "%s the Pilgrim" },
{ entry = 169, name = "Relentless Gladiator %s" },
{ entry = 170, name = "Grand Crusader %s" },
{ entry = 171, name = "%s the Argent Defender" },
{ entry = 172, name = "%s the Patient" },
{ entry = 173, name = "%s the Light of Dawn" },
{ entry = 174, name = "%s, Bane of the Fallen King" },
{ entry = 175, name = "%s the Kingslayer" },
{ entry = 176, name = "%s of the Ashen Verdict" },
{ entry = 177, name = "Wrathful Gladiator %s" },
{ entry = 188, name = "%s, Slayer of Stupid, Incompetent and Disappointing Minions" },
{ entry = 189, name = "Assistant Professor %s" },
{ entry = 190, name = "Associate Professor %s" },
{ entry = 191, name = "Professor %s" },
{ entry = 193, name = "%s, Veteran of the Alliance" },
{ entry = 194, name = "%s, Veteran of the Horde" },
{ entry = 195, name = "Private %s" },
{ entry = 196, name = "Corporal %s" },
{ entry = 197, name = "Sergeant %s" },
{ entry = 198, name = "Master Sergeant %s" },
{ entry = 199, name = "Sergeant Major %s" },
{ entry = 200, name = "Knight %s" },
{ entry = 201, name = "Knight-Lieutenant %s" },
{ entry = 202, name = "Knight-Captain %s" },
{ entry = 203, name = "Knight-Champion %s" },
{ entry = 204, name = "Lieutenant Commander %s" },
{ entry = 205, name = "Commander %s" },
{ entry = 206, name = "Marshal %s" },
{ entry = 207, name = "Field Marshal %s" },
{ entry = 208, name = "Grand Marshal %s" },
{ entry = 209, name = "Scout %s" },
{ entry = 210, name = "Grunt %s" },
{ entry = 211, name = "Sergeant %s" },
{ entry = 212, name = "Senior Sergeant %s" },
{ entry = 213, name = "First Sergeant %s" },
{ entry = 214, name = "Stone Guard %s" },
{ entry = 215, name = "Blood Guard %s" },
{ entry = 216, name = "Legionnaire %s" },
{ entry = 217, name = "Centurion %s" },
{ entry = 218, name = "Champion %s" },
{ entry = 219, name = "Lieutenant General %s" },
{ entry = 220, name = "General %s" },
{ entry = 221, name = "Warlord %s" },
{ entry = 222, name = "High Warlord %s" },
{ entry = 223, name = "%s, Hero of the Alliance" },
{ entry = 224, name = "%s, Hero of the Horde" },
{ entry = 225, name = "%s the Bloodthirsty" },
{ entry = 226, name = "%s of the Four Winds" },
{ entry = 227, name = "%s, Defender of a Shattered World" },
{ entry = 228, name = "Dragonslayer %s" },
{ entry = 229, name = "%s, Blackwing's Bane" },
{ entry = 258, name = "%s the Camel-Hoarder" },
{ entry = 259, name = "Warbringer %s" },
{ entry = 260, name = "Warbound %s" },
{ entry = 266, name = "%s, Blessed Defender of Nordrassil" },
{ entry = 267, name = "%s, Avenger of Hyjal" },
{ entry = 276, name = "%s the Flamebreaker" },
{ entry = 278, name = "Firelord %s" },
{ entry = 279, name = "Vicious Gladiator %s" },
{ entry = 280, name = "Ruthless Gladiator %s" },
{ entry = 281, name = "Cataclysmic Gladiator %s" },
{ entry = 285, name = "%s, Savior of Azeroth" },
{ entry = 287, name = "%s, Destroyer's End" },
{ entry = 303, name = "Farmer %s" },
{ entry = 308, name = "%s the Beloved" },
{ entry = 309, name = "%s the Fearless" },
{ entry = 310, name = "Zookeeper %s" },
{ entry = 311, name = "%s the Relic Hunter" },
{ entry = 314, name = "%s the Undaunted" },
{ entry = 315, name = "%s, Master of the Ways" },
{ entry = 316, name = "%s the Tranquil Master" },
{ entry = 317, name = "%s, Delver of the Vaults" },
{ entry = 318, name = "Shado-Master %s" },
{ entry = 319, name = "%s the Scenaturdist" },
{ entry = 320, name = "Tamer %s" },
{ entry = 321, name = "%s, Seeker of Knowledge" },
{ entry = 333, name = "Brawler %s" },
{ entry = 338, name = "%s the Wakener" },
{ entry = 340, name = "%s Khan" },
{ entry = 341, name = "%s the Stormbreaker" },
{ entry = 342, name = "%s, Storm's End" },
{ entry = 343, name = "Malevolent Gladiator %s" },
{ entry = 344, name = "Gob Squad Recruit %s" },
{ entry = 347, name = "Gob Squad Commando %s" },
{ entry = 348, name = "Trainer %s" },
{ entry = 349, name = "Darkspear Revolutionary %s" },
{ entry = 350, name = "Gorgeous %s" },
{ entry = 351, name = "%s the Hordebreaker" },
{ entry = 354, name = "%s the Poisoned Mind" },
{ entry = 355, name = "%s the Bloodseeker" },
{ entry = 356, name = "%s the Locust" },
{ entry = 357, name = "%s the Swarmkeeper" },
{ entry = 358, name = "%s the Prime" },
{ entry = 359, name = "%s the Manipulator" },
{ entry = 360, name = "%s the Dissector" },
{ entry = 361, name = "%s the Lucid" },
{ entry = 362, name = "%s the Wind-Reaver" },
{ entry = 365, name = "%s the Crazy Cat Lady" },
{ entry = 366, name = "%s, Defender of the Wall" },
{ entry = 367, name = "Mogu-Slayer %s" },
{ entry = 368, name = "Flameweaver %s" },
{ entry = 369, name = "Scarlet Commander %s" },
{ entry = 370, name = "Darkmaster %s" },
{ entry = 371, name = "Purified Defender %s" },
{ entry = 372, name = "Siegebreaker %s" },
{ entry = 373, name = "Stormbrewer %s" },
{ entry = 374, name = "Jade Protector %s" },
{ entry = 377, name = "%s the Crazy Cat Man" },
{ entry = 378, name = "Grievous Gladiator %s" },
{ entry = 379, name = "Prideful Gladiator %s" },
{ entry = 382, name = "%s, Conqueror of Orgrimmar" },
{ entry = 383, name = "%s, Liberator of Orgrimmar" },
{ entry = 384, name = "%s, Hellscream's Downfall" },
{ entry = 385, name = "%s the Proven Assailant" },
{ entry = 386, name = "%s the Proven Defender" },
{ entry = 387, name = "%s the Proven Healer" },
{ entry = 388, name = "Tyrannical Gladiator %s" },
{ entry = 389, name = "Fire-Watcher %s" },
{ entry = 390, name = "Mistwalker %s" },
{ entry = 391, name = "%s of the Black Harvest" },
{ entry = 392, name = "Lumberjack %s" },
{ entry = 393, name = "Timber Lord %s" },
{ entry = 394, name = "%s the Commandojack" },
{ entry = 395, name = "Architect %s" },
{ entry = 397, name = "Blood Champion %s" },
{ entry = 398, name = "%s the Manslayer" },
{ entry = 399, name = "Gnomebane %s" },
{ entry = 400, name = "%s the Dwarfstalker" },
{ entry = 401, name = "Worgen Hunter %s" },
{ entry = 402, name = "%s, Scourge of the Kaldorei" },
{ entry = 403, name = "%s, Draenei Destroyer" },
{ entry = 404, name = "%s, Terror of the Tushui" },
{ entry = 406, name = "%s, Warlord of Draenor" },
{ entry = 407, name = "%s the Butcher" },
{ entry = 408, name = "Orcslayer %s" },
{ entry = 409, name = "%s the Death Stalker" },
{ entry = 410, name = "%s, Killer of Kezan" },
{ entry = 411, name = "Troll Hunter %s" },
{ entry = 412, name = "%s, Slayer of Sin'dorei" },
{ entry = 413, name = "%s, Huojin's Fall" },
{ entry = 414, name = "Stable Master %s" },
{ entry = 415, name = "Talon King %s" },
{ entry = 416, name = "Talon Queen %s" },
{ entry = 417, name = "%s, Tarren Mill Terror" },
{ entry = 418, name = "%s, Southshore Slayer" },
{ entry = 419, name = "%s of the Frostwolves" },
{ entry = 420, name = "Prelate %s" },
{ entry = 421, name = "Conservationist %s" },
{ entry = 422, name = "%s, Spear of Vol'jin" },
{ entry = 423, name = "%s, Sword of Wrynn" },
{ entry = 424, name = "Masked Chuckler %s" },
{ entry = 425, name = "Peacekeeper %s" },
{ entry = 426, name = "%s of the Iron Vanguard" },
{ entry = 428, name = "%s the Indomitable" },
{ entry = 429, name = "%s the Mine Master" },
{ entry = 430, name = "Dockmaster %s" },
{ entry = 431, name = "%s the Soul Preserver" },
{ entry = 432, name = "%s, Scion of Rukhmar" },
{ entry = 433, name = "Spiritwalker %s" },
{ entry = 434, name = "%s, Lord of Blackrock" },
{ entry = 435, name = "%s, Lady of Blackrock" },
{ entry = 436, name = "%s the Violet Guardian" },
{ entry = 437, name = "%s the Grimrail Suplexer" },
{ entry = 438, name = "%s the Savage Hero" },
{ entry = 439, name = "%s Ironbane" },
{ entry = 440, name = "%s, Lord of War" },
{ entry = 441, name = "%s, Lady of War" },
{ entry = 442, name = "%s, Empire's Twilight" },
{ entry = 443, name = "Artisan %s" },
{ entry = 444, name = "%s, Legend of Pandaria" },
{ entry = 445, name = "Field Photographer %s" },
{ entry = 446, name = "Primal Gladiator %s" },
{ entry = 447, name = "%s, Guardian of the Alliance" },
{ entry = 448, name = "%s, Defender of the Alliance" },
{ entry = 449, name = "%s, Soldier of the Alliance" },
{ entry = 450, name = "%s, Guardian of the Horde" },
{ entry = 451, name = "%s, Defender of the Horde" },
{ entry = 452, name = "%s, Soldier of the Horde" },
{ entry = 453, name = "Wild Gladiator %s" },
{ entry = 454, name = "Warmongering Gladiator %s" },
{ entry = 455, name = "Captain %s" },
{ entry = 456, name = "%s of the Jungle" },
{ entry = 457, name = "%s, Defiler's End" },
{ entry = 458, name = "Illidari %s" },
{ entry = 462, name = "Highlord %s" },
{ entry = 463, name = "Slayer %s" },
{ entry = 464, name = "The Honorable %s" },
{ entry = 465, name = "The Prestigious %s" },
{ entry = 466, name = "The Unrelenting %s" },
{ entry = 468, name = "%s, Bound by Honor" },
{ entry = 469, name = "%s, Patron of War" },
{ entry = 470, name = "Archdruid %s" },
{ entry = 471, name = "Deathlord %s" },
{ entry = 472, name = "Grandmaster %s" },
{ entry = 473, name = "Master Assassin %s" },
{ entry = 474, name = "%s, Lord of the Reins" },
{ entry = 475, name = "%s, Guardian of G'Hanir" },
{ entry = 476, name = "%s the Groundbreaker" },
{ entry = 477, name = "%s the Fabulous" },
{ entry = 478, name = "Huntmaster %s" },
{ entry = 479, name = "Farseer %s" },
{ entry = 480, name = "Netherlord %s" },
{ entry = 481, name = "Shadowblade %s" },
{ entry = 482, name = "High Priest %s" },
{ entry = 483, name = "Field Medic %s" },
{ entry = 484, name = "%s the Dreamer" },
{ entry = 485, name = "%s, Vengeance Incarnate" },
{ entry = 486, name = "%s the Gullible" },
{ entry = 489, name = "%s, Talon's Vengeance" },
{ entry = 493, name = "%s the Chosen" },
{ entry = 494, name = "Headmaster %s" },
{ entry = 502, name = "Vindictive Gladiator %s" },
{ entry = 503, name = "%s the Unstoppable Force" },
{ entry = 504, name = "Fearless Gladiator %s" },
{ entry = 505, name = "Stylist %s" },
{ entry = 506, name = "%s the Darkener" },
{ entry = 507, name = "%s, Adventuring Instructor" },
{ entry = 508, name = "Cruel Gladiator %s" },
{ entry = 509, name = "Ferocious Gladiator %s" },
{ entry = 510, name = "Timelord %s" },
{ entry = 511, name = "%s the Tomb Raider" },
{ entry = 512, name = "Fierce Gladiator %s" },
{ entry = 513, name = "Titanslayer %s" },
{ entry = 514, name = "%s the Collector" },
{ entry = 515, name = "%s the Lightbringer" },
{ entry = 516, name = "Demonslayer %s" },
{ entry = 517, name = "Dominant Gladiator %s" },
{ entry = 518, name = "%s the Tactician" },
{ entry = 519, name = "Demonic Gladiator %s" },
{ entry = 520, name = "%s, No Good, Dirty, Rotten, Candy Stealer!" },
{ entry = 521, name = "Postmaster %s" },
{ entry = 522, name = "Prospector %s" },
{ entry = 524, name = "%s, Famed Slayer of G'huun" },
{ entry = 625, name = "%s the Horde Slayer" },
{ entry = 626, name = "%s the Alliance Slayer" },
{ entry = 627, name = "%s, Conqueror of Azeroth" },
{ entry = 628, name = "Inquisitor %s" },
{ entry = 629, name = "Esteemed %s" },
{ entry = 630, name = "%s the Admired" },
{ entry = 631, name = "%s the Purifier" },
{ entry = 632, name = "Expedition Leader %s" },
{ entry = 633, name = "Contender %s" },
{ entry = 634, name = "%s, Famed Conqueror of Dazar'alor" },
{ entry = 635, name = "%s, Famed Defender of Dazar'alor" },
{ entry = 636, name = "%s, Hero of Dazar'alor" },
{ entry = 637, name = "%s the Elite Death Knight" },
{ entry = 638, name = "%s the Elite Demon Hunter" },
{ entry = 639, name = "%s the Elite Druid" },
{ entry = 640, name = "%s the Elite Hunter" },
{ entry = 641, name = "%s the Elite Mage" },
{ entry = 642, name = "%s the Elite Monk" },
{ entry = 643, name = "%s the Elite Paladin" },
{ entry = 644, name = "%s the Elite Priest" },
{ entry = 645, name = "%s the Elite Rogue" },
{ entry = 646, name = "%s the Elite Shaman" },
{ entry = 647, name = "%s the Elite Warlock" },
{ entry = 648, name = "%s the Elite Warrior" },
{ entry = 649, name = "%s the T-Shirt Enthusiast" },
{ entry = 650, name = "Trashmaster %s" },
{ entry = 651, name = "%s, Famed Slayer of the Harbinger" },
{ entry = 654, name = "Notorious Gladiator %s" },
{ entry = 655, name = "Junkyard %s" },
{ entry = 656, name = "%s the Eternal" },
{ entry = 657, name = "%s of the Deeps" },
{ entry = 658, name = "Sparking %s" },
{ entry = 659, name = "%s, Azeroth's Champion" },
{ entry = 660, name = "Pilgrim %s the Mallet Bearer" },
{ entry = 661, name = "%s, Famed Slayer of Azshara" },
{ entry = 662, name = "Renowned Explorer %s" },
{ entry = 664, name = "%s, Veteran of the Fourth War" },
{ entry = 665, name = "Corrupted Gladiator %s" },
{ entry = 666, name = "%s, As Themselves" },
{ entry = 667, name = "%s, Servant of N'Zoth" },
{ entry = 668, name = "%s, Minion of Mayhem" },
{ entry = 669, name = "%s, Famed Slayer of N'Zoth" },
{ entry = 670, name = "%s the Uncorrupted" },
{ entry = 671, name = "%s the Awakened" },
{ entry = 672, name = "%s the Faceless One" },
{ entry = 676, name = "Cryptkeeper %s" },
{ entry = 678, name = "%s, Hand of the Archon" },
{ entry = 679, name = "Baron %s" },
{ entry = 680, name = "Baroness %s" },
{ entry = 681, name = "%s, Winter's Envoy" },
{ entry = 682, name = "Count %s" },
{ entry = 683, name = "Countess %s" },
{ entry = 684, name = "Deathbringer %s" },
{ entry = 685, name = "%s the Proud" },
{ entry = 686, name = "Sinbreaker %s" },
{ entry = 687, name = "%s the Party Herald" },
{ entry = 688, name = "Sinful Gladiator %s" },
{ entry = 689, name = "Fun Guy %s" },
{ entry = 690, name = "%s the Avowed" },
{ entry = 691, name = "Abominable %s" },
{ entry = 692, name = "Spirestalker %s" },
{ entry = 693, name = "%s the Ascended" },
{ entry = 694, name = "%s, Famed Slayer of Denathrius" },
{ entry = 698, name = "Unchained Gladiator %s" },
{ entry = 699, name = "%s, Protector of the Weald" },
{ entry = 700, name = "%s, Sword of the Primus" },
{ entry = 701, name = "Sin Eater %s" },
{ entry = 702, name = "%s, Disciple of Devotion" },
{ entry = 703, name = "%s the Tormented" },
{ entry = 704, name = "%s, Breaker of Chains" },
{ entry = 705, name = "%s, Famed Bane of the Banshee Queen" },
{ entry = 708, name = "Gauntlet Runner %s" },
{ entry = 709, name = "%s, Tower Ranger" },
{ entry = 710, name = "%s the Tormented Hero" },
{ entry = 712, name = "Cosmic Gladiator %s" },
{ entry = 713, name = "%s the [PH] TBD Title" },
{ entry = 714, name = "%s, Famed Slayer of The Banished One" },
{ entry = 715, name = "%s, Guardian of the Pattern" },
{ entry = 716, name = "Soloist %s" },
{ entry = 717, name = "%s the Cryptic" },
{ entry = 718, name = "%s the Cryptic Hero" },
{ entry = 719, name = "Fearless Spectator %s" },
{ entry = 720, name = "%s of Lordaeron" },
{ entry = 721, name = "Eternal Gladiator %s" },
{ entry = 722, name = "%s, Maw Walker" },
{ entry = 723, name = "Veilstrider %s" },
{ entry = 724, name = "%s, Hero of Fate" },
{ entry = 725, name = "%s the Shrouded" },
{ entry = 727, name = "%s the Shrouded Hero" },
{ entry = 728, name = "%s, Honorary Dryad" },
{ entry = 729, name = "Crimson Gladiator %s" },
{ entry = 730, name = "%s the Worldbreaker" },
{ entry = 731, name = "%s the Thundering Hero" },
{ entry = 732, name = "Soupervisor %s" },
{ entry = 733, name = "Birdwatcher %s" },
{ entry = 734, name = "Khansguard %s" },
{ entry = 735, name = "%s, Ally of Dragons" },
{ entry = 736, name = "Intrepid Explorer %s" },
{ entry = 737, name = "%s of Iskaara" },
{ entry = 738, name = "%s the Thundering" },
{ entry = 739, name = "Isles Racer %s" },
{ entry = 740, name = "Malicious %s" },
{ entry = 741, name = "%s, Knight of Feathersworth" },
{ entry = 742, name = "%s the Elite Evoker" },
{ entry = 743, name = "Crimson Legend %s" },
{ entry = 744, name = "%s, Paragon of the Obsidian Brood" },
{ entry = 745, name = "%s, Agent of the Black Prince" },
{ entry = 746, name = "Merchant Artisan %s" },
{ entry = 747, name = "Personal Crafter %s" },
{ entry = 748, name = "%s, Famed Slayer of Raszageth" },
{ entry = 749, name = "%s the Storm-Eater" },
{ entry = 750, name = "Forbidden Reach Racer %s" },
{ entry = 751, name = "Reverse Racer %s" },
{ entry = 752, name = "Legend %s" },
{ entry = 753, name = "Skyscourge %s" },
{ entry = 760, name = "Lionguard %s" },
{ entry = 761, name = "%s the Key Master" },
{ entry = 762, name = "%s the Forbidden" },
{ entry = 763, name = "Kalimdor Racer %s" },
{ entry = 765, name = "%s the Reconciler" },
{ entry = 766, name = "Obsidian Gladiator %s" },
{ entry = 767, name = "Obsidian Legend %s" },
{ entry = 768, name = "Smelly %s" },
{ entry = 769, name = "%s, Barter Boss" },
{ entry = 770, name = "%s the Smoldering" },
{ entry = 771, name = "%s the Smoldering Hero" },
{ entry = 772, name = "%s, Heir to the Void" },
{ entry = 773, name = "%s, Famed Slayer of Sarkareth" },
{ entry = 774, name = "%s, Sniffenseeker" },
{ entry = 775, name = "Field Researcher %s" },
{ entry = 776, name = "Zaralek Cavern Racer %s" },
{ entry = 777, name = "Whelptender %s" },
{ entry = 778, name = "Ama'shan %s" },
{ entry = 781, name = "%s Unparalleled" },
{ entry = 782, name = "%s the Inquisitive" },
{ entry = 783, name = "%s of the Infinite" },
{ entry = 784, name = "Eastern Kingdoms Racer %s" },
{ entry = 785, name = "%s of the Tyr's Guard" },
{ entry = 786, name = "%s the Dreaming" },
{ entry = 787, name = "%s, Honorary Historian" },
{ entry = 788, name = "Honorary Preservationist %s" },
{ entry = 789, name = "%s the Storm Rider" },
{ entry = 790, name = "Outland Racer %s" },
{ entry = 791, name = "Dream Racer %s" },
{ entry = 792, name = "Isles Ace %s" },
{ entry = 793, name = "Emerald Ace %s" },
{ entry = 794, name = "Verdant Legend %s" },
{ entry = 795, name = "Verdant Gladiator %s" },
{ entry = 796, name = "Blossom Bringer %s" },
{ entry = 797, name = "%s, Famed Slayer of Fyrakk" },
{ entry = 798, name = "Battle Mender %s" },
{ entry = 799, name = "%s the Blazing" },
{ entry = 800, name = "%s the Dreaming Hero" },
{ entry = 801, name = "%s, Dream Defender" },
{ entry = 802, name = "The Forbidden %s" },
{ entry = 803, name = "Draconic Gladiator %s" },
{ entry = 804, name = "Draconic Legend %s" },
{ entry = 805, name = "%s, Isles Archivist" },
{ entry = 806, name = "%s the Draconic" },
{ entry = 807, name = "%s the Draconic Hero" },
{ entry = 809, name = "Northrend Racer %s" },
{ entry = 810, name = "Plunderlord %s" },
{ entry = 815, name = "Swabbie %s" },
{ entry = 816, name = "Deck Hand %s" },
{ entry = 817, name = "Swashbuckler %s" },
{ entry = 818, name = "Buccaneer %s" },
{ entry = 819, name = "First Mate %s" },
{ entry = 821, name = "%s, Champion of the Dragonflights" },
{ entry = 822, name = "%s the Tempered Hero" },
{ entry = 823, name = "Immortal Spelunker %s" },
{ entry = 824, name = "High Explorer %s" },
{ entry = 825, name = "Timerunner %s" },
{ entry = 826, name = "%s, Paragon of the Mists" },
{ entry = 827, name = "%s, Claw of Eternus" },
{ entry = 828, name = "Strategist %s" },
{ entry = 829, name = "Forged Warlord %s" },
{ entry = 830, name = "Forged Marshal %s" },
{ entry = 831, name = "Queenslayer %s" },
{ entry = 832, name = "%s, Awakened Hero" },
{ entry = 833, name = "Forged Gladiator %s" },
{ entry = 834, name = "Forged Legend %s" },
{ entry = 835, name = "Ascension Breaker %s" },
{ entry = 836, name = "%s, Famed Slayer of Ansurek" },
{ entry = 837, name = "%s, Slayer of the Deeps" },
{ entry = 838, name = "Deephauler %s" },
{ entry = 839, name = "Machine Whisperer %s" },
{ entry = 840, name = "Honorary Councilmember %s" },
{ entry = 841, name = "Lamplighter %s" },
{ entry = 842, name = "Thread-Spinner %s" },
{ entry = 843, name = "%s, Machine-Warden" },
{ entry = 844, name = "%s, Witness of the Kirin Tor" },
{ entry = 845, name = "%s, Seeker of Loot" },
{ entry = 846, name = "Detective %s" },
{ entry = 847, name = "Silksinger %s" },
{ entry = 848, name = "Anub'%s" },
{ entry = 849, name = "%s, Hand of the Vizier" },
{ entry = 850, name = "%s the Bountiful" },
{ entry = 851, name = "Echochaser %s" },
{ entry = 852, name = "Grizzly Hills Hiker %s" },
{ entry = 853, name = "Plaguelands Survivor %s" },
{ entry = 854, name = "%s the Tempered" },
{ entry = 855, name = "Skyrocketer %s" },
{ entry = 856, name = "Classic Enthusiast %s" },
{ entry = 857, name = "Outland Enthusiast %s" },
{ entry = 858, name = "Northrend Enthusiast %s" },
{ entry = 859, name = "Cataclysm Enthusiast %s" },
{ entry = 860, name = "Pandaria Enthusiast %s" },
{ entry = 861, name = "Draenor Enthusiast %s" },
{ entry = 862, name = "Broken Isles Enthusiast %s" },
{ entry = 863, name = "Zandalar Enthusiast %s" },
{ entry = 864, name = "Kul Tiras Enthusiast %s" },
{ entry = 865, name = "Shadowlands Enthusiast %s" },
{ entry = 866, name = "Dragon Isles Enthusiast %s" },
{ entry = 867, name = "%s the Enterprising" },
{ entry = 868, name = "%s the Enterprising Hero" },
{ entry = 869, name = "Khaz Algar Racer %s" },
{ entry = 870, name = "Molten Core Prospector %s" },
{ entry = 871, name = "Karazhan Graduate %s" },
{ entry = 872, name = "Breaknecker %s" },
{ entry = 873, name = "Delver %s" },
{ entry = 874, name = "Infinite Delver %s" },
{ entry = 875, name = "Landlubber %s" },
{ entry = 876, name = "%s the Treasured" },
{ entry = 878, name = "High Roller %s" },
{ entry = 879, name = "%s the Explosive" },
{ entry = 880, name = "%s, Famed Slayer of The Chrome King" },
{ entry = 881, name = "%s, Liberator of Undermine" },
{ entry = 882, name = "Darkfuse Diplomat %s" },
{ entry = 883, name = "Trade-Duke %s" },
{ entry = 884, name = "Prized Gladiator %s" },
{ entry = 885, name = "Prized Warlord %s" },
{ entry = 886, name = "Prized Marshal %s" },
{ entry = 887, name = "Prized Legend %s" },
{ entry = 888, name = "%s, the Real Deal" },
{ entry = 889, name = "Junkmaestro %s" },
{ entry = 892, name = "Part-Timer %s" },
{ entry = 893, name = "%s, Employee of the Month" },
{ entry = 894, name = "%s, the Reel Deal" },
}