blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation / Wiki
    url: https://example.com/wiki
    about: Please check the docs before opening an issue.
  - name: 💬 Quick support
    url: https://www.azerothdevs.com/index.php
    about: For usage or installation questions.
