EventsData = {
    { eventEntry = 1, name = "Midsummer Fire Festival" },
    { eventEntry = 2, name = "Winter Veil" },
    { eventEntry = 3, name = "Darkmoon Faire" },
    { eventEntry = 6, name = "New Year's Eve" },
    { eventEntry = 7, name = "Lunar Festival" },
    { eventEntry = 8, name = "Love is in the Air" },
    { eventEntry = 9, name = "Noblegarden" },
    { eventEntry = 10, name = "Children's Week " },
    { eventEntry = 11, name = "Harvest Festival" },
    { eventEntry = 12, name = "Hallow's End" },
    { eventEntry = 13, name = "Elemental Invasions" },
    { eventEntry = 14, name = "Stranglethorn Fishing Extravaganza Announce" },
    { eventEntry = 15, name = "Stranglethorn Fishing Extravaganza Fishing Pools" },
    { eventEntry = 16, name = "Gurubashi Arena Booty Run" },
    { eventEntry = 17, name = "Scourge Invasion" },
    { eventEntry = 18, name = "Call to Arms: Alterac Valley!" },
    { eventEntry = 19, name = "Call to Arms: Warsong Gulch!" },
    { eventEntry = 20, name = "Call to Arms: Arathi Basin!" },
    { eventEntry = 21, name = "Call to Arms: Eye of the Storm!" },
    { eventEntry = 22, name = "AQ War Effort" },
    { eventEntry = 23, name = "Darkmoon Faire Building" },
    { eventEntry = 24, name = "Brewfest" },
    { eventEntry = 25, name = "Nights" },
    { eventEntry = 26, name = "Pilgrim's Bounty" },
    { eventEntry = 27, name = "Edge of Madness, Gri'lek" },
    { eventEntry = 28, name = "Edge of Madness, Hazza'rah" },
    { eventEntry = 29, name = "Edge of Madness, Renataki" },
    { eventEntry = 30, name = "Edge of Madness, Wushoolay" },
    { eventEntry = 31, name = "Arena Tournament" },
    { eventEntry = 32, name = "L70ETC Concert" },
    { eventEntry = 33, name = "Dalaran: Minigob" },
    { eventEntry = 34, name = "Brew of the Month October" },
    { eventEntry = 35, name = "Brew of the Month November" },
    { eventEntry = 36, name = "Brew of the Month December" },
    { eventEntry = 37, name = "Brew of the Month January" },
    { eventEntry = 38, name = "Brew of the Month February" },
    { eventEntry = 39, name = "Brew of the Month March" },
    { eventEntry = 40, name = "Brew of the Month April" },
    { eventEntry = 41, name = "Brew of the Month May" },
    { eventEntry = 42, name = "Brew of the Month June" },
    { eventEntry = 43, name = "Brew of the Month July" },
    { eventEntry = 44, name = "Brew of the Month August" },
    { eventEntry = 45, name = "Brew of the Month September" },
    { eventEntry = 46, name = "L70 ETC Shattrath Announce" },
    { eventEntry = 47, name = "L70 ETC Shattrath" },
    { eventEntry = 48, name = "Wintergrasp Alliance Defence" },
    { eventEntry = 49, name = "Wintergrasp Horde Defence" },
    { eventEntry = 50, name = "Pirates' Day" },
    { eventEntry = 51, name = "Day of the Dead" },
    { eventEntry = 52, name = "Winter Veil: Gifts" },
    { eventEntry = 53, name = "Call to Arms: Strand of the Ancients!" },
    { eventEntry = 54, name = "Call to Arms: Isle of Conquest!" },
    { eventEntry = 55, name = "PvP Season 3 - Vengeful (TBC)" },
    { eventEntry = 56, name = "PvP Season 4 - Brutal (TBC)" },
    { eventEntry = 57, name = "PvP Season 5 - Deadly (WotLK)" },
    { eventEntry = 58, name = "PvP Season 6 - Furious (WotLK)" },
    { eventEntry = 59, name = "PvP Season 7 - Relentless (WotLK)" },
    { eventEntry = 60, name = "PvP Season 8 - Wrathful (WotLK)" },
    { eventEntry = 61, name = "Zalazane's Fall" },
    { eventEntry = 62, name = "Stranglethorn Fishing Extravaganza Turn-ins" },
    { eventEntry = 63, name = "Kalu'ak Fishing Derby Turn-ins" },
    { eventEntry = 64, name = "Kalu'ak Fishing Derby Fishing Pools" },
    { eventEntry = 65, name = "Perry Gatner" },
    { eventEntry = 67, name = "AT Event Trigger (Tirion Speech)" },
    { eventEntry = 68, name = "AT Event Trigger (Horde Event)" },
    { eventEntry = 69, name = "AT Event Trigger (Alliance Event)" },
    { eventEntry = 70, name = "WoW's 9th Anniversary" },
    { eventEntry = 71, name = "WoW's 10th Anniversary" },
    { eventEntry = 72, name = "Fireworks Spectacular" },
    { eventEntry = 73, name = "Hourly Bells" },
    { eventEntry = 76, name = "Children of Goldshire" },
    { eventEntry = 78, name = "Summer seasonal fish" },
    { eventEntry = 79, name = "Diurnal fishing event" },
    { eventEntry = 80, name = "Nocturnal fishing event" },
    { eventEntry = 81, name = "L70ETC Grim Guzzler" },
    { eventEntry = 82, name = "Operation: Gnomeregan" },
    { eventEntry = 83, name = "Warsong Hold Invasion" },
    { eventEntry = 84, name = "AT ValKyr invasion" },
    { eventEntry = 85, name = "Honor Hold Hellfire" },
    { eventEntry = 86, name = "PvP Season 9 - Vicious (Cataclysm)" },
    { eventEntry = 87, name = "PvP Season 10 - Ruthless (Cataclysm)" },
    { eventEntry = 88, name = "PvP Season 11 - Cataclysmic (Cataclysm)" },
    { eventEntry = 89, name = "WoW's 20th Anniversary" },
}
